### PR TITLE
#406 Update outdated examples from README.

### PR DESCRIPTION
**Pull request by alex-semenyuk**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#407` is in scope.

**Comment by yegor256** [comment]
@alex-semenyuk thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#407` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#407`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#407` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#407` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6035](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1260](http://www.0crat.com/u/kkamkou).

**Pull request merged**
