### PR TITLE
(#1262) TailOf is now based on Reversed

### PR DESCRIPTION
**Pull request by victornoel**
This is for #1262, I had to improve the test because it wasn't catching ordering bugs.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1264](https://github.com/yegor256/cactoos/issues/1264) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1264](https://github.com/yegor256/cactoos/issues/1264) is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/C63314D6Z/a8a06e8c-7095-40d8-8f2e-f6038b829de8); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by iakunin** [comment]
@victornoel pretty concise pull request, that I have nothing to comment =)

@paulodamaso looks good to merge.

**Comment by victornoel** [comment]
@paulodamaso ping :)

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#1264](https://github.com/yegor256/cactoos/issues/1264) is not in the agenda of @iakunin[/z](https://www.0crat.com/u/iakunin), can't retrieve data and time of add

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iakunin[/z](https://www.0crat.com/u/iakunin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (17 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Job [#1264](https://github.com/yegor256/cactoos/issues/1264) is not in the agenda of @iakunin[/z](https://www.0crat.com/u/iakunin), can't inspect

**Comment by 0crat** [comment]
The job [#1264](https://github.com/yegor256/cactoos/issues/1264) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
