### PR TITLE
#189 AllOf, AnyOf, And, Or

### PR DESCRIPTION
**Pull request by VsSekorin**
As per #189

### CODE REVIEW

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin looks like we duplicated each other, see #192

**Comment by VsSekorin** [comment]
@yegor256 Why don't you create ctor`Iterable<T>, Func<T, Scalar<Boolean>>` if you delete IterableAsBoolean?

**Comment by VsSekorin** [comment]
@yegor256 Your PR is very large and covers not only issue 189. Then I close my PR, right?

**Comment by yegor256** [comment]
@VsSekorin yes, please close the PR

**Pull request closed without merging**
