### PR TITLE
Fixed examples in readme.md

### PR DESCRIPTION
**Pull request by advasileva**
According to issue #1670, I compiled and ran the code examples in `README.md`. Some of them didn't compile or crashed with an exception, so I fixed them

### CODE REVIEW

**Comment by victornoel** [comment]
@0crat assign me

**Comment by advasileva** [comment]
Should I update this PR somehow?

**Comment by victornoel** [comment]
@advasileva sorry I haven't had the time to review it yet, I will get back to you here when I do.
I've assigned it to me because we don't have any dev nor reviewers available in the project unfortunately.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1671](https://github.com/yegor256/cactoos/issues/1671), since the job is not in scope anymore

**Pull request merged**
