### PR TITLE
(#1417) Move to github actions instead of travis/appveyor

### PR DESCRIPTION
**Pull request by victornoel**
This is for #1417.

Inspired from https://github.com/llorllale/cactoos-matchers/pull/174

### CODE REVIEW

**Comment by victornoel** [comment]
@yegor256 can it be possible to activate in this repository whatever is necessary for this PR to have some checks done? Thank you

**Comment by yegor256** [comment]
@victornoel no need to activate anything, GitHub will pick us the configuration file automatically

**Comment by victornoel** [comment]
@yegor256 ok, so it will be enabled only once merged, is that it? Thank you

**Comment by victornoel** [comment]
@rultor merge

**Comment by yegor256** [comment]
@victornoel yes, correct

**Comment by 0crat** [comment]
Job [#1486](https://github.com/yegor256/cactoos/issues/1486) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#1486](https://github.com/yegor256/cactoos/issues/1486) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
