### PR TITLE
Project report 2019-12-05

### PR DESCRIPTION
**Pull request by paulodamaso**
Project report 2019-12-05 and commit lint removal.

### CODE REVIEW

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.2`

**Comment by paulodamaso** [comment]
@rultor stop

**Comment by 0crat** [comment]
Job [#1257](https://github.com/yegor256/cactoos/issues/1257) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/1257#issuecomment-562163826))

@paulodamaso Job `gh:yegor256/cactoos#1257` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/1257#issuecomment-562163826))

@paulodamaso The job [#1257](https://github.com/yegor256/cactoos/issues/1257) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/1257#issuecomment-562163826))

@paulodamaso Pull request [#1257](https://github.com/yegor256/cactoos/issues/1257) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1257` is not assigned, can't get performer

**Pull request merged**
