### PR TITLE
#578 moved matchers to src/main/org/cactoos/matchers

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Moved the matchers over to src/test. @yegor256 Should we gather them in a package there?

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#586](https://github.com/yegor256/cactoos/issues/586) is now in scope, role is `REV`

**Comment by svendiedrichsen** [comment]
@yegor256 Found 5 matcher implementations. One under `func` and 4 at the root of `org.cactoos`. Should we put them all in a package `matchers` within `src/test`?

**Comment by 0crat** [comment]
This pull request [#586](https://github.com/yegor256/cactoos/issues/586) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by neonailol** [comment]
@yegor256 i think matchers should stay in main project, as they are useful for users of the library

**Comment by yegor256** [comment]
@svendiedrichsen I think I agree with @neonailol Let's move them to `src/main` and gather everything in `org.cactoos.matchers` package.

**Comment by svendiedrichsen** [comment]
ok. i'll move them.

**Comment by svendiedrichsen** [comment]
I have moved the matchers to `src/main`. But I only see the usefulness for test code which can be satisfied by delivering a cactoos test artefact.

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by neonailol** [comment]
@yegor256 pr can be merged

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+210](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8920](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#586](https://github.com/yegor256/cactoos/issues/586) is now out of scope

**Pull request merged**
