### PR TITLE
#439 Or More ctors

### PR DESCRIPTION
**Pull request by VsSekorin**
As per #439

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#440` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#440` assigned to @fabriciofx, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@fabriciofx resigned from `gh:yegor256/cactoos#440`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#440` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Pull request merged**
