### PR TITLE
Prototype Shuffled iterator

### PR DESCRIPTION
**Pull request by funivan**
Use cactoos in own project (simple game) Here is my use case:
```java

new Cycled<>(
    new Shuffled<>(
        new ListOf<>(
            new Color(255, 150, 0),
            new Color(100, 200, 100),
            new Color(250, 50, 50)
        )
    )
)
```
I need randomly output any color on request.

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#434` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#434` assigned to @fabriciofx, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@fabriciofx resigned from `gh:yegor256/cactoos#434`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#434` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by funivan** [comment]
@yegor256 Can you explain why @kkamkou assigned via 0crat to this PR?

**Comment by yegor256** [comment]
@funivan our bug, please ignore this

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#434` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6035](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1260](http://www.0crat.com/u/kkamkou).

**Pull request merged**
