### PR TITLE
#62 Do not use static Arrays.asList(...)

### PR DESCRIPTION
**Pull request by Maratori**
Replace `Arrays.asList(...)` in `IterableOf` ctor with explicit definition of `Iterator`.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#627](https://github.com/yegor256/cactoos/issues/627) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#627](https://github.com/yegor256/cactoos/issues/627) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/431913502). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@Maratori I don't like it, to be honest -- don't we have an implementation of Iterator in Cactoos, which we could use here? Point is, how do we test this anonymous implementation of iterator, how do we know it works?

Besides, it's not even clear if the original ticket is still valid; I see it was very old and very broad, with no clear conclusions in it.

**Comment by Maratori** [comment]
@amihaiemil Please have a look updated PR.
Now I use `StickyIterator` instead of anonymus class. I've added new tests to it as well.

Also I believe we should rename `StickyIterator` to `IteratorOf` in the future.

**Comment by amihaiemil** [comment]
@Maratori Now the PR is way too big. Originally, there was a single file changed. Do the change there (replace that anonymous iterator just there) and clearly explain why StickyIterator will do the job. also, write a unit test for that method (in which you change the iterator from List.iterator()  to StickyIterator), to prove it still works).

That's it, no need to change 12 files. And if you think StickyIterator should be renamed, you can open a ticket about it and discuss with the architect there, but that is outside the scope of this PR :)

**Comment by Maratori** [comment]
@amihaiemil Ok. Let's do it another way.

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+555](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9649](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#627](https://github.com/yegor256/cactoos/issues/627) is now out of scope

**Pull request closed without merging**
