### PR TITLE
(#964) Don't use compound names for decorators

### PR DESCRIPTION
**Pull request by llorllale**
This PR is for #964:
* Fixed `list` and `map` packages
* left puzzle for continuing refactor

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#979](https://github.com/yegor256/cactoos/issues/979) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#979` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#979](https://github.com/yegor256/cactoos/issues/979) is now out of scope

**Pull request merged**
