### PR TITLE
(#1065) Applied new naming convention in text package

### PR DESCRIPTION
**Pull request by Iprogrammerr**
As described in #1065. New naming convention was applied to Joined, Normalized and Trimmed. Puzzle were updated to continue.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1066](https://github.com/yegor256/cactoos/issues/1066) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1066](https://github.com/yegor256/cactoos/issues/1066) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/a135e318-2e0c-4c04-a4c1-f8b177a269c7); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1066` already assigned to @fabriciofx, can't assign to @fabriciofx

**Comment by Iprogrammerr** [comment]
@fabriciofx ping.

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1066#issuecomment-465379626))

@llorllale The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1066](https://github.com/yegor256/cactoos/issues/1066), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#1066](https://github.com/yegor256/cactoos/issues/1066) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/39b3daea-55cf-4070-acb5-1bd6a89c00e0); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@Iprogrammerr can you just replace the calls to `MatcherAssert` with `Assertion.affirm()` in the tests you modified as well as replace usage of `Matchers` static methods with their OO equivalent if there are some?

**Comment by Iprogrammerr** [comment]
@victornoel Here you have.

**Comment by victornoel** [comment]
@Iprogrammerr thanks
@llorllale good to merge

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#1066](https://github.com/yegor256/cactoos/issues/1066) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Pull request merged**
