### PR TITLE
#764: Head input implementation

### PR DESCRIPTION
**Pull request by memoyil**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#807](https://github.com/yegor256/cactoos/issues/807) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#807](https://github.com/yegor256/cactoos/issues/807) is assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/1222140984); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by 0crat** [comment]
Job [#807](https://github.com/yegor256/cactoos/issues/807) is already in scope

**Comment by 0crat** [comment]
GitHub issue is still open, won't close

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/807#issuecomment-386139070))

@llorllale This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#807](https://github.com/yegor256/cactoos/issues/807) is [in scope](http://www.zerocracy.com/policy.html#14) for 43min
  * The role is `REV`
  * The job is assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) for [40min](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @memoyil[/z](https://www.0crat.com/u/memoyil): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23807%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by memoyil** [comment]
@0crat help

**Comment by 0crat** [comment]
> @0crat help ([here](https://github.com/yegor256/cactoos/issues/807#issuecomment-386140585))

@memoyil Can't understand "help", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#807](https://github.com/yegor256/cactoos/issues/807) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@memoyil what was the issue?

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request closed without merging**
