### PR TITLE
#390 : Remove Decoded Encoded URL

### PR DESCRIPTION
**Pull request by memoyil**
Remove Decoded Encoded URL

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#391` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @memoyil, total is [+60](http://www.0crat.com/u/memoyil).

**Comment by memoyil** [comment]
@yegor256 Test coverage  test failed because of high coverage of Decoded/Encoded URL Tests. What we will do ?

**Comment by yegor256** [comment]
@memoyil add some new unit tests for some other classes

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#391` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#391`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#391` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#391` is not in scope

**Pull request merged**
