### PR TITLE
MD5, SHA-1 and SHA-256 hashes functions

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #338. It depends on #335 .

### CODE REVIEW

**Comment by memoyil** [comment]
@fabriciofx we should put them in the codecs package WDYT?

**Comment by fabriciofx** [comment]
@memoyil I think we should first ask to @yegor256 what he thinks. @yegor256 WDYT? :)

**Comment by g4s8** [comment]
@fabriciofx @memoyil @yegor256 I would not include crypto related code into cactoos library because:
1. This code is platform dependent. Any machine may contain different security provider implementations. Moreover any project (that using cactoos as a dependency) may include third party security provider implementation as a library. The one and the other may change `MessageDigest.getInstance` result unobviously. 
2. It increase complexity by extending the scope from `text+IO+collections` to `text+IO+collections+crypto`

**Comment by llorllale** [comment]
@fabriciofx please close this PR as both issues you [mentioned](https://github.com/yegor256/cactoos/pull/339#issue-131898162) were cancelled by yourself

**Comment by llorllale** [comment]
@fabriciofx closing as per what I [said](https://github.com/yegor256/cactoos/pull/339#issuecomment-382078771)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request closed without merging**
