### PR TITLE
#392 : Increase test coverage

### PR DESCRIPTION
**Pull request by memoyil**
Increases the test coverage

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#393` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @memoyil, total is [+75](http://www.0crat.com/u/memoyil).

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@memoyil thanks for that! Please, contribute with more tests like that.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#393` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#393`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#393` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#393` is not in scope

**Pull request merged**
