### PR TITLE
introduced new ctors

### PR DESCRIPTION
**Pull request by ashtonhogan**
This is the code for this [issue](https://github.com/yegor256/cactoos/issues/754)

### CODE REVIEW

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
This pull request [#775](https://github.com/yegor256/cactoos/issues/775) is assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/1171039374); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by SharplEr** [comment]
@llorllale  The author refuse from his PR. So you can close it.

**Comment by llorllale** [comment]
@SharplEr it's still a pr. Please review accordingly

**Comment by SharplEr** [comment]
@ashtonhogan Please fix checks.

**Comment by SharplEr** [comment]
@ashtonhogan if you don't want to merge this PR, then close it. Otherwise, you have to fix problems with checks first.

**Comment by ashtonhogan** [comment]
@SharplEr Were you automatically assigned to take over my dog food? That sucks.

**Comment by llorllale** [comment]
@ashtonhogan please help us out by fixing the checkstyle issues (see the travis log)

**Comment by ashtonhogan** [comment]
@llorllale I'm happy to help handover the work but I won't be doing further dev work because of the reasons listed [here](https://github.com/ashtonhogan/home/tree/master/articles/why-you-should-not-contribute-to-open-source/README.md)

**Comment by SharplEr** [comment]
@llorllale I think we see here some personal drama here)

**Comment by ashtonhogan** [comment]
@SharplEr I'm trying hard not to make any drama and point out only the facts

**Comment by llorllale** [comment]
@ashtonhogan I see, thanks.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@009e3d45-fe1c-4664-83fc-70da2c75bbad, thread: AsyncFlush-5
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.DomParser[112] java.lang.IllegalArgumentException: Invalid XML: "<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
"
com.sun.org.apache.xerces.internal.parsers.DOMParser[257] org.xml.sax.SAXParseException: The element type "hr" must be terminated by the matching end-tag "</hr>".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#775](https://github.com/yegor256/cactoos/issues/775) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request closed without merging**
