### PR TITLE
README - compared with stream API

### PR DESCRIPTION
**Pull request by g4s8**
Added comparations with stream API for `Mapped`, `Joined` and updated "JDK 8" for `Filtered`.

### CODE REVIEW

**Comment by llorllale** [comment]
@g4s8 I think it'd be better to demonstrate the flattening of iterables using `Joined` and `Mapped` by adding an example to the `Iterables/Collections/Lists/Sets` section.

Also, the travis build fails. Please open a ticket for this PR (*not* the build failure) and edit your commit msg accordingly.

**Comment by llorllale** [comment]
@g4s8 see #1061

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1058` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
