### PR TITLE
#677 removed ctors for list package

### PR DESCRIPTION
**Pull request by nick318**
#677 removed ctors for list package

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#694](https://github.com/yegor256/cactoos/issues/694) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#694](https://github.com/yegor256/cactoos/issues/694) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/512014166). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/694#issuecomment-367283991))

@g4s8 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#694](https://github.com/yegor256/cactoos/issues/694) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 15hr
  * The role is `REV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [14hr](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @nick318[/z](https://www.0crat.com/u/nick318): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23694%27%7D) (restricted area)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@yegor256 Could you resign me here?

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/694#issuecomment-368815001))

@yegor256 The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#694](https://github.com/yegor256/cactoos/issues/694), please stop working. Reason for job resignation: Order was cancelled

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/694#issuecomment-368815626))

@yegor256 The job [#694](https://github.com/yegor256/cactoos/issues/694) is now out of scope

**Pull request closed without merging**
