### PR TITLE
(#1274) Make addAll properly call internal addAll

### PR DESCRIPTION
**Pull request by strattonw**
This is for issue: https://github.com/yegor256/cactoos/issues/1274

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1275](https://github.com/yegor256/cactoos/issues/1275) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1275](https://github.com/yegor256/cactoos/issues/1275) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/98b7155c-ebbf-4803-82f9-03e47cc33cd5); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1275` already assigned to @fanifieiev, can't assign to @fanifieiev

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (8 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by fanifieiev** [comment]
@sereshqua I know there is only one review comment from me, not 3 as expected, but the change in this PR is so tiny, that I could not post any other review comments. 
I do understand that it violates our policy, but it is an edge case.

**Comment by 0crat** [comment]
The job [#1275](https://github.com/yegor256/cactoos/issues/1275) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by sereshqua** [comment]
@fanifieiev I do understand your point, but there are no edge cases for this rule :)

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by paulodamaso** [comment]
@rultor release tag is `0.44`

**Pull request merged**
