### PR TITLE
#794 upgrade qulice

### PR DESCRIPTION
**Pull request by krzyk**
#794 
- upgraded qulice
- removed puzzle
- fixed all issues found by new qulice version (e.g. @author and @version tags are now prohibited)

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#834](https://github.com/yegor256/cactoos/issues/834) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#834](https://github.com/yegor256/cactoos/issues/834) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1272116372); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by Vatavuk** [comment]
@krzyk No comments from my side, everything looks good.

**Comment by Vatavuk** [comment]
@llorllale good to merge

**Comment by llorllale** [comment]
@krzyk 513 files!!

**Comment by Vatavuk** [comment]
@llorllale :DD I don't see another way than to remove tags from all those files...

**Comment by llorllale** [comment]
@Vatavuk he could've removed *some* of the tags while not upgrading qulice, and leaving a puzzle for the rest...

**Comment by Vatavuk** [comment]
@krzyk true, but we can remove those tags with one unix command...

**Comment by llorllale** [comment]
@Vatavuk correct, but my eyeballs+brain can't focus through 513 changed files in order to make sure that this simple change was reproduced correctly in all of them.

**Comment by Vatavuk** [comment]
@llorllale true, I switched to "I believe him" mode when I saw those changes:). Maybe we can create puzzles for each package.

**Comment by llorllale** [comment]
@krzyk please limit the scope of this PR to 50 files. Leave a puzzle for the rest. I think we can "safely" review this simple change in groups of 50 files.

**Comment by krzyk** [comment]
@llorllale it is not possible, if I remove @author and @version from some of the files previous qulice will complain, if I don't remove them next version will complain. I'm between hammer and an anvil.

So the solution would be to:
- use old qulice
- remove author, version tags, and replace `/**` to `/*` in header
- add 3 excludes in each of the 50 files:
```
// @checkstyle Header (500 lines)
// @checkstyle JavadocTags (500 lines)
// @checkstyle RegexpSingleline (1 lines)
```

And then someone would need to upgrade qulice. And then again in 50 file batches remove thos excludes.
That would make this simple automatic change a 513/50  * 2 = 22 issues, spaning few weeks and 22 * (30 mins (or maybe 15?) + 15 mins + 8 mins + 8 mins). That would make it a cost of 1012 - 1342 mins cost, it would basically made each and everyone in the proejct working on upgrading qulice. It is not worth it.

I think that you can review it using some kind of automation, the only changes that should be here are:
- removal of todo
- upgrade qulice
- remove of all lines that start with ` * @author`
- remove of all lines that start with ` * @version`
- replace the first line of every java file with `/*`

**Comment by Vatavuk** [comment]
@llorllale @krzyk 
I've run these commands to see changes other than `@author` `@version`
To see what lines were removed:
`git diff -U0 7601514f7d1c5358f6 4738a00c1953795024e | grep -F --invert "+ * @author"| grep -F --invert "+ * @version" | grep "^\-"`
Three classes were changed in addition to tags and pom: `ProcTest`, `CallableOfTest` and `TimedFuncTest`
Minor formating changes and one simplified lambda change. 

To see what lines were added:
`git diff -U0 7601514f7d1c5358f6 4738a00c1953795024e | grep -F --invert "+ * @author"| grep -F --invert "+ * @version" | grep "^\+"`
Same three classes.

I think we are good...

**Comment by krzyk** [comment]
@Vatavuk Yeah, those 3 cases: `ProcTest`, `CallableOfTest` and `TimedFuncTest` were reported by qulice so I updated those.

**Comment by llorllale** [comment]
@Vatavuk thanks

@krzyk looks ok I think... please fix the new merge conflicts and I'll check again

**Comment by krzyk** [comment]
@llorllale updated

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#834](https://github.com/yegor256/cactoos/issues/834) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@Vatavuk According to our Policy:
> The code reviewer found at least three problems in the code

As far as I can see, no issues were found here.
Please, confirm that you'll try to find at least three problems in the code in future.

**Comment by Vatavuk** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
