### PR TITLE
#672: Add test cases for all ctors of SolidBiFunc

### PR DESCRIPTION
**Pull request by proshin-roman**
This pull request is for #672: it adds new test cases for all ctors of SolidBiFunc.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#727](https://github.com/yegor256/cactoos/issues/727) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#727](https://github.com/yegor256/cactoos/issues/727) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/650577726). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by proshin-roman** [comment]
@neonailol Thanks for your comments! Now I've added messages for assertions, refactored the code to make it more OOP, but wasn't able to get rid of double-assert at all - one test case still contains two assertions, but IMO it's better than boilerplate code with executors/synchronization (I would just copy implementation of `RunsInThreads` class). So please review the pull request again!

**Comment by neonailol** [comment]
@proshin-roman thanks, all looking good got me now

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by proshin-roman** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @neonailol[/z](https://www.0crat.com/u/neonailol), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#727](https://github.com/yegor256/cactoos/issues/727) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
