### PR TITLE
 Fix some more TeeInput tests

### PR DESCRIPTION
**Pull request by victornoel**
This is for #1392

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1394](https://github.com/yegor256/cactoos/issues/1394) is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/32986fbe-eb75-4e2f-b6c1-de52969490f2); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@marceloamadeu thx, it is done

**Comment by marceloamadeu** [comment]
@victornoel `AppVeyor build failed`... What's the problem? Tks

**Comment by victornoel** [comment]
@marceloamadeu I think the CI has some temporary issue, let me try to push again to re-trigger it

**Comment by victornoel** [comment]
@paulodamaso there is a problem with the CI and it is not related to this PR.

**Comment by paulodamaso** [comment]
@victornoel Yeah, appveyor run is broken.

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@marceloamadeu please make sure your comments would be mostly about design problems, but NOT rather cosmetic issues

**Comment by marceloamadeu** [comment]
@sereshqua ok...  thx.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
