### PR TITLE
Changing the architect name on README.md

### PR DESCRIPTION
**Pull request by paulodamaso**
Changing the architect name on README.md

### CODE REVIEW

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by iakunin** [comment]
@paulodamaso rultor cannot merge this PR because of invalid commit-message:
```
753487f: subject does not match regex [^\(#[0-9]+\) [^\s].{13,50}]
```

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1214` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
