### PR TITLE
Test coverage

### PR DESCRIPTION
**Pull request by g4s8**
Test coverage badge on README page

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8 I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@g4s8 I don't think it works. Codecov.io gave me some "token", which I have to put somewhere. Can you explain what to do next?

**Comment by g4s8** [comment]
@yegor256  It should work out-of-box, token needs for private repositories only. 
I think the problem in this line: [`- mvn clean`](https://github.com/yegor256/cactoos/blob/master/.travis.yml#L9)
travis clean build after coverage report generating. Why do we need to do this? Is it safe to remove this line?

**Comment by yegor256** [comment]
@g4s8 let's see what happens after 4c5f8fb

**Comment by yegor256** [comment]
@g4s8 works fine, thanks!

**Pull request merged**
