### PR TITLE
(#1137) Simplified responsibility and implementation of FirstOf

### PR DESCRIPTION
**Pull request by scrobot**
This is for #1137. I replaced params `Func<T, Boolean> cond` and `Iterable<T> src` to `Filtered<T>` in `FirstOf<>()` constructor, and ofcourse fixed tests.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1160](https://github.com/yegor256/cactoos/issues/1160) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1160](https://github.com/yegor256/cactoos/issues/1160) is assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/dbd463b5-192b-4df6-b96f-72bf563cd20e); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@rultor merge

**Comment by llorllale** [comment]
@scrobot check your commit msgs as per the note in https://github.com/yegor256/cactoos#how-to-contribute

**Comment by vzurauskas** [comment]
@scrobot I use [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) (see Changing Multiple Commit Messages) when I'm in this situation (there might be a better solution that I'm not aware of though).

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (21 days), architects (@llorllale) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#1160](https://github.com/yegor256/cactoos/issues/1160) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by vzurauskas** [comment]
@sereshqua Why is quality bad?

**Comment by vzurauskas** [comment]
@sereshqua ping

**Comment by sereshqua** [comment]
@vzurauskas hi! i've seen that you haven't found any issues during the CR, that's why quality is bad

**Comment by vzurauskas** [comment]
@sereshqua See this comment: https://github.com/yegor256/cactoos/pull/1160#pullrequestreview-261586776

**Comment by sereshqua** [comment]
@vzurauskas i am sorry, i did not treat at the result of CR and did not count this comment as an 1 issue, quality should be acceptable

**Pull request merged**
