### PR TITLE
Fix typo in name BiFuncEnvelope

### LINKED ISSUE #1648: BiFuncEnveloppe - typo?
I think `BiFuncEnveloppe` is a typo and should be renamed to `BiFuncEnvelope`

### PR DESCRIPTION
**Pull request by alex-semenyuk**
Close #1648

### CODE REVIEW

**Comment by victornoel** [comment]
@yegor256 apparently xcop is not working anymore

**Comment by victornoel** [comment]
@alex-semenyuk thank you

**Comment by victornoel** [comment]
@rultor merge

**Comment by yegor256** [comment]
@victornoel see https://github.com/g4s8/xcop-action/issues/4

**Pull request merged**
