### PR TITLE
(#1205) Fixed the failing qulice checks for the excluded files listed in pom.xml after updating qulice-maven-plugin  

### PR DESCRIPTION
**Pull request by fanifieiev**
This pull request is for issue [1205](https://github.com/yegor256/cactoos/issues/1205)

Previously a number of classes/files were excluded from `qulice` check listed in `pom.xml`, so that the build passed.
This pull request includes the excluded classes/files with appropriate fixes and lets `qulice` check them.

There are some `Findbugs` issues raised by `qulice`:
http://findbugs.sourceforge.net/bugDescriptions.html#EQ_UNUSUAL
[INFO] >> M D Eq: org.cactoos.map.MapEnvelope.equals(Object) is unusual At MapEnvelope.java:[line 151] [INFO] >> M D Eq: org.cactoos.iterable.IterableOf.equals(Object) is unusual At IterableOf.java:[line 149] [INFO] >> M D Eq: org.cactoos.text.TextEnvelope.equals(Object) is unusual At TextEnvelope.java:[line 80] [INFO] >> M D Eq: org.cactoos.collection.CollectionEnvelope.equals(Object) is unusual At CollectionEnvelope.java:[line 155].

That seems to be false positive as the implementation looks good, but unusual, so I suppressed this kind of issue with the help of [SuppressFBWarnings](http://findbugs.sourceforge.net/api/edu/umd/cs/findbugs/annotations/SuppressFBWarnings.html)

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1208](https://github.com/yegor256/cactoos/issues/1208) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1208](https://github.com/yegor256/cactoos/issues/1208) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/81615774-500d-4d03-ae4d-f029c89c726a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@742ae47f-2674-48fd-afc8-2556a3780c2e, thread: pool-220-thread-1
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: java.util.concurrent.locks.ReentrantLock@47b33030[Locked by thread PQ-C6MATTB7E]
```

[0.50.17](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#1208, Comment: 542895453

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@742ae47f-2674-48fd-afc8-2556a3780c2e, thread: pool-220-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: java.util.concurrent.locks.ReentrantLock@47b33030[Locked by thread PQ-C6MATTB7E]
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: java.util.concurrent.locks.ReentrantLock@47b33030[Locked by thread PQ-C6MATTB7E]
```

[0.50.17](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#1208, Action: `created`

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1208#issuecomment-543258218))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1208](https://github.com/yegor256/cactoos/issues/1208) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @fanifieiev[/z](https://www.0crat.com/u/fanifieiev): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231208%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1208#issuecomment-544965228))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1208](https://github.com/yegor256/cactoos/issues/1208) is [in scope](http://www.zerocracy.com/policy.html#14) for 10days
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [10days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @fanifieiev[/z](https://www.0crat.com/u/fanifieiev): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231208%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1208#issuecomment-545599157))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1208](https://github.com/yegor256/cactoos/issues/1208) is [in scope](http://www.zerocracy.com/policy.html#14) for 12days
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [12days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @fanifieiev[/z](https://www.0crat.com/u/fanifieiev): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231208%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by paulodamaso** [comment]
@fanifieiev Please correct the PR description; it must address the issue, as http://www.zerocracy.com/policy.html#42

**Comment by fanifieiev** [comment]
> @fanifieiev Please correct the PR description; it must address the issue, as http://www.zerocracy.com/policy.html#42

@paulodamaso  done

**Comment by paulodamaso** [comment]
@fanifieiev Please correct the PR description too, not just the title. Please put a link on the description, so we can easily navigate between the PR and its generating issue and understand what problem the PR is proposing to solve and how it is solving that easily

**Comment by fanifieiev** [comment]
> @fanifieiev Please correct the PR description too, not just the title. Please put a link on the description, so we can easily navigate between the PR and its generating issue and understand what problem the PR is proposing to solve and how it is solving that easily

@paulodamaso Done

**Comment by paulodamaso** [comment]
@fanifieiev Great, thanks!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by fanifieiev** [comment]
@paulodamaso seems like someone introduced more violations while my PR was waiting for rev.
I am gonna merge my forked branch with upstream and fix that issue, and then push to my forked branch.

**Comment by paulodamaso** [comment]
@fanifieiev Okay, thanks

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by fanifieiev** [comment]
@paulodamaso I think there is a small problem.
Only 3 of 4 checks passed. 
codecov/patch step seems to have failed.

**Comment by paulodamaso** [comment]
@fanifieiev this check is somewhat bugged, and sometimes it does not reflects current code status

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1208#issuecomment-546901490))

@paulodamaso Job [#1208](https://github.com/yegor256/cactoos/issues/1208) is closed, can't start order

**Comment by 0crat** [comment]
Code review was too long (21 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1208](https://github.com/yegor256/cactoos/issues/1208) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
