### PR TITLE
#665 AsyncFunc tests

### PR DESCRIPTION
**Pull request by SharplEr**
For #665 

**Problem**
There aren't tests for following ctors:
```Java
public AsyncFunc(final Proc<X> proc, final ThreadFactory fct)
public AsyncFunc(final Proc<X> proc, final ExecutorService exec)
```

**Solution**
Added two test for both untested ctors. Where tested thread name to ensure `Proc` executed with specific `ThreadFactory`/`ExecutorService` and a side effect in `Proc` to ensure the specific `Proc` has been called as in other tests (by using `CountDownLatch` ).

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#713](https://github.com/yegor256/cactoos/issues/713) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#713](https://github.com/yegor256/cactoos/issues/713) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/591738498). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by SharplEr** [comment]
@neonailol ping.

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SharplEr** [comment]
@yegor256 ping)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @neonailol[/z](https://www.0crat.com/u/neonailol), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#713](https://github.com/yegor256/cactoos/issues/713) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by elenavolokhova** [comment]
@neonailol According to our [QA rules](http://datum.zerocracy.com/pages/policy.html#42)
> The code reviewer found at least three problems in the code.

No issues were found during review.
Please, **confirm** that you'll try to find at least three design problems in next reviews.

**Comment by neonailol** [comment]
@elenavolokhova i confirm

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
