### PR TITLE
#720: Add more tests for TeeInput class.

### PR DESCRIPTION
**Pull request by proshin-roman**
Pull request for #720: adds more unit tests for TeeInput class. But still, not all ctors are covered by tests as it would require more time and would produce a huge - non-reviewable - pull request.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#732](https://github.com/yegor256/cactoos/issues/732) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#732](https://github.com/yegor256/cactoos/issues/732) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/691635242). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by proshin-roman** [comment]
@neonailol ping

**Comment by proshin-roman** [comment]
@neonailol Thanks for your comment! I will fix it as soon as pull request #731 is merged (then I will be able to use just a single assert that will check both results).

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#732](https://github.com/yegor256/cactoos/issues/732), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
This pull request [#732](https://github.com/yegor256/cactoos/issues/732) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/791616551); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by proshin-roman** [comment]
@neonailol I've refactored all tests using a new TeeInputHasResultMatcher (that was introduced in #721). Please review the pull request again. Thanks!

**Comment by neonailol** [comment]
@proshin-roman thanks, I will review it soon 

_Sent from my ZenFone 2 Laser (ZE601KL) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by proshin-roman** [comment]
@yegor256 something went wrong with this issue (0crat doesn't respond). Could you try to merge the pull request, please?

**Comment by proshin-roman** [comment]
@yegor256 merge the pull request please

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#732](https://github.com/yegor256/cactoos/issues/732) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by elenavolokhova** [comment]
@0crat status

**Comment by elenavolokhova** [comment]
@neonailol According to our Policy:
>The code reviewer found at least three problems in the code

Only one issue was found in this PR. 
Please, confirm that you will try to find at least three problems next time.

Also, 
>Messages in a job always start with a name of a user they are addressed to

This message was not addressed to anyone:
>All tests contain multiple assertions, please correct it according to http://www.yegor256.com/2017/05/17/single-statement-unit-tests.html

Please, avoid such issues in future too.

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/732#issuecomment-376617044))

@elenavolokhova This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#732](https://github.com/yegor256/cactoos/issues/732) is not in scope
  * The job is waiting quality review verdict by @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) for 1days
  * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) will receive 15 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23732%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by elenavolokhova** [comment]
@0crat quality bad as far as @neonailol was reassigned from this PR and @fabriciofx didn't reviewed it actually

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
