### PR TITLE
Added org.cactoos.collection.StickyCollection

### PR DESCRIPTION
**Pull request by YashchenkoN**
#421

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#424` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#424` assigned to @fabriciofx, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@fabriciofx resigned from `gh:yegor256/cactoos#424`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#424` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#424` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6035](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1260](http://www.0crat.com/u/kkamkou).

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/424#issuecomment-356791332))

@fabriciofx This is what I know about this job, as in §32:

  * The job [#424](https://github.com/yegor256/cactoos/issues/424) is not in scope

**Comment by fabriciofx** [comment]
@yegor256 This job is assigned to me (in my agenda), but 0crat does not recognized it. Could you check it? Thanks!

**Comment by yegor256** [comment]
@fabriciofx it's a bug in the agenda, ignore it for now please, very soon we will polish the agenda automatically

**Pull request merged**
