### PR TITLE
#711: Change normalized string asstring with ReplacedText

### PR DESCRIPTION
**Pull request by memoyil**

### CODE REVIEW

**Comment by llorllale** [comment]
@memoyil always [report what is broken](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken) first.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by llorllale** [comment]
@memoyil just realized that the related issue was in the title. Please help us avoid confusions such as this one by becoming familiar with our [QA](http://www.zerocracy.com/policy.html#30) rules

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by memoyil** [comment]
@llorllale ok, thank you.

**Pull request merged**
