### PR TITLE
#1395: Fix TeeInput tests to check file content

### PR DESCRIPTION
**Pull request by fabriciofx**
Per #1395 

- Fix `TeeInputFromInputTest` tests to check file content
- Fix `TeeInputFromUriTest` tests to check message content
- Remove puzzle

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1431](https://github.com/yegor256/cactoos/issues/1431) is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss), here is [why](https://www.0crat.com/footprint/C63314D6Z/3e40f2ff-c43e-4e29-919f-b5bb657e6036); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @victornoel[/z](https://www.0crat.com/u/victornoel) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by andreoss** [comment]
@fabriciofx 
Using `LengthOf` as a i/o trigger and ignoring its result seems a bit strange to me, but this practice can be found in many other tests.
@victornoel 
Otherwise, looks good.

**Comment by fabriciofx** [comment]
@andreoss `LengthOf` just returns the size of the file/stream. Although the test doesn't check its size, it checks the content, which is the real interest here.

**Comment by fabriciofx** [comment]
@victornoel ping

**Review by victornoel — APPROVED** [review]
@fabriciofx that looks good. Have you checked there are no other cases like this one in the code base?

Btw, you were asking the other day about asking 0crat to wait: I find it comfortable to ask it as soon as the PR is created, but you have to ask in the ticket, not in the PR!

**Comment by fabriciofx** [comment]
@victornoel 
>Have you checked there are no other cases like this one in the code base?
Yeah. There aren't more cases.

> I find it comfortable to ask it as soon as the PR is created, but you have to ask in the ticket, not in the PR!
Ops! My mistake! Thanks for this advice.

**Comment by victornoel** [comment]
@fabriciofx great, thx for verifying :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by fabriciofx** [comment]
> @fabriciofx great, thx for verifying :)

@victornoel  welcome!

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1431#issuecomment-687274342))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1431](https://github.com/yegor256/cactoos/issues/1431) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `REV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231431%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat out

**Pull request merged**
