### PR TITLE
Refactoring Base64Text (#929)

### PR DESCRIPTION
**Pull request by Iprogrammerr**
Refactored Base64Text as described in #929.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#974](https://github.com/yegor256/cactoos/issues/974) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@Iprogrammerr you need to leave a puzzle for continuing the refactor

**Comment by llorllale** [comment]
@rultor merge

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#974` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#974](https://github.com/yegor256/cactoos/issues/974) is now out of scope

**Pull request merged**
