### PR TITLE
(#1074) apply new naming convention in text package

### PR DESCRIPTION
**Pull request by longstone**
Continued to refactor the class names as mentioned in #1074.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1080](https://github.com/yegor256/cactoos/issues/1080) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1080](https://github.com/yegor256/cactoos/issues/1080) is assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/75b33818-81f5-4773-a5dd-146f4d6b2076); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by Iprogrammerr** [comment]
@longstone Choose a few tests, replace usage of MatcherAssert with Assertion and we are good to go.

**Comment by longstone** [comment]
@Iprogrammerr done

**Comment by Iprogrammerr** [comment]
@longstone Good job. 
@llorllale PR is ready to merge.

**Comment by longstone** [comment]
image

I think I need someone with write access to the repository or should I open a new PR?

**Comment by Iprogrammerr** [comment]
@longstone Couldn't you just edit the PR?

**Comment by longstone** [comment]
@Iprogrammerr now it was possible :)

**Comment by Iprogrammerr** [comment]
@longstone That is good. @llorllale PR is ready to merge.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#1080](https://github.com/yegor256/cactoos/issues/1080) is now out of scope

**Comment by 0crat** [comment]
This pull request [#1080](https://github.com/yegor256/cactoos/issues/1080) is assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/7a66c53b-dd4b-43bc-be91-af71bd697cdc); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr) resigned from [#1080](https://github.com/yegor256/cactoos/issues/1080), since the job is not in scope anymore

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Pull request merged**
