### PR TITLE
Make all basic types throw Exception instead of IOException

### PR DESCRIPTION
**Pull request by aliceice**
As per #518

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#710](https://github.com/yegor256/cactoos/issues/710) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#710](https://github.com/yegor256/cactoos/issues/710) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/591733331). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by neonailol** [comment]
@yegor256 good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by neonailol** [comment]
@aliceice please update pr with latest code from master branch

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by aliceice** [comment]
@neonailol

I‘m sorry, but I will not be able to update my PR as I won‘t have access to Internet for a while.

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by neonailol** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/710#issuecomment-371760722))

@neonailol The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#710](https://github.com/yegor256/cactoos/issues/710), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
This pull request [#710](https://github.com/yegor256/cactoos/issues/710) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/680935691). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#710](https://github.com/yegor256/cactoos/issues/710), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
This pull request [#710](https://github.com/yegor256/cactoos/issues/710) is assigned to @rexim[/z](https://www.0crat.com/u/rexim), here is [why](https://www.0crat.com/footprint/C63314D6Z/780960089). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by rexim** [comment]
@aliceice hello! how's your Internet after two weeks? Do you have a chance to update your PR?

**Comment by 0crat** [comment]
The user @rexim[/z](https://www.0crat.com/u/rexim) resigned from [#710](https://github.com/yegor256/cactoos/issues/710), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @rexim[/z](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment]
This pull request [#710](https://github.com/yegor256/cactoos/issues/710) is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1091277576); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by krzyk** [comment]
@aliceice Can you work on this PR (merge the latest master)?

**Comment by krzyk** [comment]
@llorllale I think @aliceice is no longer with us (I don't see here in the team table) so I think it would be best to close this PR and allow someone else to fix the issue.

**Comment by krzyk** [comment]
@0crat help

**Comment by 0crat** [comment]
> @0crat help ([here](https://github.com/yegor256/cactoos/issues/710#issuecomment-382983300))

@krzyk Can't understand "help", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by krzyk** [comment]
@llorllale OK, but she didn't respond any previous inquiries and is not active on github since Feb 22 (and of course she is not in the zerocracy list).

**Comment by llorllale** [comment]
@aliceice closing due to inactivity

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/710#issuecomment-383622058))

@llorllale The job [#710](https://github.com/yegor256/cactoos/issues/710) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by elenavolokhova** [comment]
@krzyk According to our Policy:
> The code reviewer found at least three problems in the code 
> All problems found by the code reviewer were addressed by the pull request author

 In #728 you posted 3 comments about issues in code, so you did your job as a reviewer and payment was needed. The second rule was violated, PR was not merged, that's why quality was not good, but acceptable.

In this case there were no issues found in code itself, PR was closed due to author's inactivity, so review was not completed as expected. That is why quality is bad here.

Does it make sense? Please, correct me if you think my decision is not correct or is not fair.

**Comment by krzyk** [comment]
@elenavolokhova ok, makes sense

**Pull request closed without merging**
