### PR TITLE
Add `toString`, `equals` & `hashCode` to `text.Sticky`

### PR DESCRIPTION
**Pull request by andreoss**
For #1582:

- Base `text.Sticky` on `TextEnvelope`

### CODE REVIEW

**Comment by victornoel** [comment]
@andreoss thx, btw no need to create an issue if you create a PR directly :) (at the risk of being refused of course)

**Comment by victornoel** [comment]
@rultor merge

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 42 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
