### PR TITLE
(#1565) Improve generic variance for `org.cactoos.iterator`

### PR DESCRIPTION
**Pull request by DmitryBarskov**
For #1565:

Add covariant constructor params for

- `IteratorEnvelope`
- `Synced`
- `Sorted`
- `Skipped`
- `Sliced`
- `Shuffled`
- `NoNulls`

### CODE REVIEW

**Comment by victornoel** [comment]
@0crat status

**Comment by victornoel** [comment]
@0crat status

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1611#issuecomment-860062952))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1611](https://github.com/yegor256/cactoos/issues/1611) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231611%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat in

**Review by andreoss — APPROVED** [review]

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
