### PR TITLE
#811: InheritanceLevel for unrelated classes should be negative

### PR DESCRIPTION
**Pull request by proshin-roman**
Pull request for #811.

I've changed the logic of InheritanceLevel.java so that it returns Integer.MIN_VALUE (instead of MAX_VALUE) when the classes are not related. As well I've fixed all dependencies which rely on this logic. And finally, I've fixed affected tests.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#833](https://github.com/yegor256/cactoos/issues/833) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#833](https://github.com/yegor256/cactoos/issues/833) is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1272067105); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by proshin-roman** [comment]
@krzyk I've fixed all comments - please, review the pull request again.

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#833](https://github.com/yegor256/cactoos/issues/833) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +20 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
