### PR TITLE
(#1259) Sorted Set with custom comparator

### PR DESCRIPTION
**Pull request by fanifieiev**
This PR is for #1259

### CODE REVIEW

**Comment by fanifieiev** [comment]
@paulodamaso 
Question:
image
Do you now where that test `org.cactoos.experimental.TimedTest` is located ?? The repo does not contain it.

**Comment by paulodamaso** [comment]
@fanifieiev Please update your branch,  `Timed` was introduced in #1000

**Comment by 0crat** [comment]
This pull request [#1279](https://github.com/yegor256/cactoos/issues/1279) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/787dadcc-12b3-47a1-9268-ab06e837a393); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1279#issuecomment-581594134))

@paulodamaso This pull request [#1279](https://github.com/yegor256/cactoos/issues/1279) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/5ef66905-df7b-4ece-a3e1-c389c896917b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1279#issuecomment-581594134))

@paulodamaso There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@377a78bde909, thread: PQ-C63314D6Z
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [comment, job, issue, repo, cause, _parent_sig, flow, login]
```

[0.51.0](https://github.com/zerocracy/farm): CID: [22701f4d-5817-401c-8869-638368d49a1c](https://www.0crat.com/footprint/C63314D6Z/22701f4d-5817-401c-8869-638368d49a1c), Type: "Order was canceled"

**Comment by 0crat** [comment]
Job [#1279](https://github.com/yegor256/cactoos/issues/1279) is already in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by fanifieiev** [comment]
@paulodamaso I have no idea why that build fails. It does not fail locally and the failure is related to `TimedTest`.

**Comment by paulodamaso** [comment]
@fanifieiev PLease solve these conflicts

**Comment by paulodamaso** [comment]
@fanifieiev Please merge with master, there are too much files being altered in this PR

**Comment by fanifieiev** [comment]
@paulodamaso Please have a look.

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
