### PR TITLE
996: Making ListEnvelope public

### PR DESCRIPTION
**Pull request by piotrkot**
Making ListEnvelope public

### CODE REVIEW

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @llorllale[/z](https://www.0crat.com/u/llorllale) please review this and merge or reject

**Comment by llorllale** [comment]
@piotrkot please fix your commit msgs (a47be69e5153aab13ab4cf1f18f70c95720e2d55 is unacceptable)

**Comment by piotrkot** [comment]
@llorllale what do you mean? The first two messages were not acceptable. The third one was fine for Travis.

**Comment by llorllale** [comment]
@piotrkot the message on a47be69e5153aab13ab4cf1f18f70c95720e2d55 is not acceptable

**Comment by llorllale** [comment]
@piotrkot ping

**Comment by piotrkot** [comment]
@llorllale Can you explain what should be in the commit message?
Normally, I put message describing what I actually did in the commit. So, the first one is fixing the issue, The second is fixing qulice warning, and as sole purpose of the third change was to satisfy travis' regex check, that's what is says.
Now, if you don't like it I will make a rollback of the previous commit (a47be69), which will still be a dummy commit. How should I name it?

**Comment by llorllale** [comment]
@piotrkot you can just squash them all into a single commit with a sensible message

**Comment by piotrkot** [comment]
@llorllale OMG, I hate git. I couldn't make it with rebase and squash. Instead, tried with `git reset --soft` and `git commit`. Any better?

**Comment by piotrkot** [comment]
@llorllale ping

**Comment by llorllale** [comment]
@piotrkot they're still visible [here](https://github.com/yegor256/cactoos/pull/1073/commits)

**Comment by piotrkot** [comment]
@llorllale Well, I don't know how to do it, then.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1073` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
