### PR TITLE
(#1335) LengthOf is now just a Scalar of Long

### PR DESCRIPTION
**Pull request by victornoel**
First step of #1335: LengthOf is not a Number anymore

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1535](https://github.com/yegor256/cactoos/issues/1535) is assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/0690f702-fe1d-4585-ad96-6eea7394db1f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @victornoel[/z](https://www.0crat.com/u/victornoel) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@baudoliver7 We need to wait for https://github.com/llorllale/cactoos-matchers/pull/221 and then https://github.com/yegor256/cactoos/issues/1531 for this to be able to build. I will ping you back when it's ok :)

**Comment by baudoliver7** [comment]
@victornoel Ok

**Comment by baudoliver7** [comment]
@victornoel I'm always waiting :)

**Comment by victornoel** [comment]
@baudoliver7 I know, I haven't forgot, this nor any of the other opened PRs

**Comment by baudoliver7** [comment]
@victornoel Just to remind you that if code review takes too long time, you will be exposed to penalties as ARC [§55](http://www.zerocracy.com/policy.html#55)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@baudoliver7 I know, if I were paid, maybe I would worry about it :) I've removed from this job and will add you again once it's ready to be reviewed. I am waiting for another ticket to be solved first

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1535#issuecomment-770185687))

@victornoel The user @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) resigned from [#1535](https://github.com/yegor256/cactoos/issues/1535), please stop working. Reason for job resignation: Order was cancelled

**Comment by baudoliver7** [comment]
@victornoel Good ! Don't hesitate to assign it to me again when all things are ready :)

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1535](https://github.com/yegor256/cactoos/issues/1535); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1535](https://github.com/yegor256/cactoos/issues/1535); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by victornoel** [comment]
Closing this, even with #1531 it's not building, we will have to wait for llorllale/cactoos-matchers#220 to be fixed first

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1535` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#1535](https://github.com/yegor256/cactoos/issues/1535) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
