### PR TITLE
(#1194) HeadOf.java: refactored implementation to use Sliced

### PR DESCRIPTION
**Pull request by ryoku**
This is for issue #1194

Refactor of `HeadOf` using `Sliced `primitive.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1271](https://github.com/yegor256/cactoos/issues/1271) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1271](https://github.com/yegor256/cactoos/issues/1271) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/74875662-5309-46e0-9932-1e5ecf2c9e8c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by ryoku** [comment]
@fanifieiev Absolutely right: refactoring done.

**Comment by fanifieiev** [comment]
@paulodamaso Please merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1271](https://github.com/yegor256/cactoos/issues/1271) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by sereshqua** [comment]
@fanifieiev please make sure you will find at least 3 issues during next CR, thanks :)

**Comment by fanifieiev** [comment]
@sereshqua Sure, will do.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Pull request merged**
