### PR TITLE
LengthOf#274 Text, Input, Iterable and Iterator

### PR DESCRIPTION
**Pull request by ixmanuel**
### [Skip this comment, see next entry please]
This PR has included the PR #354 ArrayOf

### Notes:
- If LenghtOfInput(Input) tries to count single visual characters, then this PR can be used instead of ArrayOf PR #354 and later, this PR should be patched because actually it calculates the length as bytes.length and thus, the length for non-ascii chars doesn't match the length of single visual characters, because non-ascii chars have two or more bytes for their representation.

- If LenghtOf(Input) tries to calculate the size of bytes, then this PR must be updated later with the following considerations: Length for Inputs must be removed from the new LengthOf because semantically it is different and we could consider to rename it to  SizeOfInput(Input).

### CODE REVIEW

**Comment by ixmanuel** [comment]
@yegor256 @fabriciofx 

This PR:
- LengthOf(Text) counts the elements.
- LengthOf(Iterable, Iterator) counts the elements.
- LengthOf(Input) the size in bytes.

Thus, it is counterintuitive so, an alternative:
- CountOf  instead of LengthOf to count elements in Text, Bytes, Input, Iterable and Iterator.
- SizeOf to calculate the size in bytes for Text, Bytes and Input

**Comment by fabriciofx** [comment]
@ixmanuel I vote for `CountOf`. @yegor256 WDYT?

**Comment by ixmanuel** [comment]
This PR is outdated and we have to decide. See above.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#355` was not in scope

**Pull request closed without merging**
