### PR TITLE
#1261: Remove CollectionOf

### PR DESCRIPTION
**Pull request by andreoss**
- Bump `cactoos-matchers` to 0.19
- Remove classes

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1446](https://github.com/yegor256/cactoos/issues/1446) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/93a6aa14-1249-4271-844c-98335f0e5c96); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @victornoel[/z](https://www.0crat.com/u/victornoel) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@andreoss please, something is wrong in the build process. Can you look it?

**Comment by andreoss** [comment]
@fabriciofx Sorry, I wasn't expected that @0crat will dispatch draft PR. 

The build will be working after https://github.com/llorllale/cactoos-matchers/issues/167

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/1446#issuecomment-687909255); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by fabriciofx** [comment]
@andreoss ok, no problem! :)

**Comment by andreoss** [comment]
@fabriciofx Ready for review

**Review by fabriciofx — APPROVED** [review]
@andreoss it seems fine to me. @victornoel can you merge it, please?

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 35 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
