### PR TITLE
#796 expanded BiFuncOf ctors

### PR DESCRIPTION
**Pull request by Vatavuk**
I've created new ctor for BiFuncOf for #796

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#822](https://github.com/yegor256/cactoos/issues/822) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#822](https://github.com/yegor256/cactoos/issues/822) is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1260886777); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by krzyk** [comment]
@Vatavuk according to the policy one PR should be for one problem, and here those changes don't depend on each other either.

So so I propose to change the PR here for #796 only, and create new one for #812

**Comment by Vatavuk** [comment]
@krzyk fixed in 1d10a03, and updated description

**Comment by krzyk** [comment]
@llorllale good to merge

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#822](https://github.com/yegor256/cactoos/issues/822) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@krzyk Sorry, my bad. Thanks for confirmation!

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Pull request merged**
