### PR TITLE
#652 - Added tests for ctors for the MapOf class

### PR DESCRIPTION
**Pull request by driver733**
As per #652.

I have written the missing tests for the constructors for the MapOf class. Now, all of the constructors are properly tested.

One of the tests was not included as it fails (see #659).

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#660](https://github.com/yegor256/cactoos/issues/660) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#660](https://github.com/yegor256/cactoos/issues/660) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/470351420). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@driver733 PR title here as well pls

**Comment by driver733** [comment]
@amihaiemil Done.

**Comment by amihaiemil** [comment]
@driver733 I see. The PR looks good. Next time, when a unit test you wrote is failing, just add ``@Ignore`` and leave a ``todo`` puzzle over it, which will turn into a task and someone will fix it later. Now, I see that the opened issue was accepted, so let's leave it like this.

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by driver733** [comment]
@amihaiemil 
https://github.com/yegor256/cactoos/pull/660#issuecomment-366307985
Thank you for your advice. I will do that in the future.

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by driver733** [comment]
@yegor256 ping.

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.

No issues were found during code review. Please confirm that you'll try to find at least three problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka I confirm. Although an issue was found here (see my comment) :D

**Comment by ypshenychka** [comment]
@amihaiemil Thank you. I would count it as an issue, if it is fixed by performer right in this PR. But nothing has changed so far:)

**Comment by ypshenychka** [comment]
@0crat Quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+390](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+835](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10389](https://www.0crat.com/u/yegor256)

**Pull request merged**
