### PR TITLE
Optimizing Imports

### PR DESCRIPTION
**Pull request by portlek**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1164](https://github.com/yegor256/cactoos/issues/1164) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1164](https://github.com/yegor256/cactoos/issues/1164) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/e9c35514-e9ac-4491-8f39-5f149f5b749d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@portlek what is the issue solved by this PR? Add a small description of the changes made and why. Also the build is failing.

**Comment by 0crat** [comment]
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1164](https://github.com/yegor256/cactoos/issues/1164) is now out of scope

**Comment by 0crat** [comment]
Pull request [#1164](https://github.com/yegor256/cactoos/issues/1164) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request closed without merging**
