### PR TITLE
#677 removed ctors with iterator for And's classes

### PR DESCRIPTION
**Pull request by nick318**
In the issue #677 explained why iterator as a parameter is a bad idea, so I just removed ctors with `Iterator` for `And`, `AndInThreads`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#693](https://github.com/yegor256/cactoos/issues/693) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#693](https://github.com/yegor256/cactoos/issues/693) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/511904843). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@nick318 Looks ok, but let's wait for https://github.com/yegor256/cactoos/pull/687 to be merged, then you will have to merge master into your branch and make sure to fix/remove the tests that are using the ``Iterator`` ctors.

**Comment by amihaiemil** [comment]
@nick318 Can you merge with master? #687 has been merged recently and some tests have to be changed there, since you removed some ctors in ``AndInThreads``

**Comment by amihaiemil** [comment]
@nick318 ping

**Comment by amihaiemil** [comment]
@nick318 ping

**Comment by nick318** [comment]
@amihaiemil done

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@nick318 yes, I'll review it in a few hours :)

**Comment by nick318** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 this can be merged

**Comment by nick318** [comment]
@amihaiemil take a look at https://github.com/zerocracy/datum/issues/306#issuecomment-369161767. It seems we have no luck to merge it

**Comment by amihaiemil** [comment]
@nick318 I see... then, if @yegor256 does not respond soon (say until tomrrow evening) can you close it so  I don't lose points? But leep the branch so you can make a future PR.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by amihaiemil** [comment]
@ypshenychka Can you review this one soon, there are only 2 days left

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka I confirm -- I did find one, though, I let the author know about the dependency to a previously merged PR, which he probably wouldn't have noticed otherwise.

**Comment by amihaiemil** [comment]
@ypshenychka pls give the verdict, it's the 10th day

**Comment by amihaiemil** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/693#issuecomment-369860981))

@ypshenychka The job [#693](https://github.com/yegor256/cactoos/issues/693) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@amihaiemil Just in time :) Sorry. For some reason I'm receiving part of notifications to Spam. Will try to deal with that issue.

**Pull request merged**
