### PR TITLE
#1349: Remove todo

### PR DESCRIPTION
**Pull request by andreoss**
- Just remove todo
- Actual work was done in https://github.com/yegor256/cactoos/pull/1435

### CODE REVIEW

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @victornoel[/z](https://www.0crat.com/u/victornoel) please review this and merge or reject

**Review by victornoel — APPROVED** [review]
@andreoss thanks

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1452` is not assigned, can't get performer

**Pull request merged**
