### PR TITLE
#335  Bytes to hexadecimal

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #335.

### CODE REVIEW

**Comment by yegor256** [comment]
@fabriciofx maybe we should name it `HexOf`?

**Comment by fabriciofx** [comment]
@yegor256 I agree and did it. Could you review it, please?

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#337` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#337` was not in scope

**Pull request closed without merging**
