### PR TITLE
(#951) Use 00 matchers and Assertion in time classes

### PR DESCRIPTION
**Pull request by victornoel**
This is for #951,

I covered the time package and also used `Assertion`.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1077](https://github.com/yegor256/cactoos/issues/1077) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1077](https://github.com/yegor256/cactoos/issues/1077) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/3a25a0c8-7a68-4709-8ad0-2d3c80ea8d0a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@llorllale 0crat didn't seem to hear you… !

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1077#issuecomment-469480005))

@llorllale The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1077](https://github.com/yegor256/cactoos/issues/1077), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#1077](https://github.com/yegor256/cactoos/issues/1077) is assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/f366905d-8210-4748-be85-682f463b221e); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@Iprogrammerr ping?

**Comment by Iprogrammerr** [comment]
@victornoel Nothing to to be added. @llorllale PR is ready to merge.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#1077](https://github.com/yegor256/cactoos/issues/1077) is now out of scope

**Pull request merged**
