### PR TITLE
#1258 added extra constructor

### PR DESCRIPTION
**Pull request by dgarus**
[#1258](https://github.com/yegor256/cactoos/issues/1258)

### CODE REVIEW

**Comment by 0crat** [comment]
@dgarus[/z](https://www.0crat.com/u/dgarus) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@dgarus Thank you!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1317` is not assigned, can't get performer

**Pull request merged**
