### PR TITLE
Removed calls to size() and cache from IterableAsList

### PR DESCRIPTION
**Pull request by Timmeey**
No more calls to size() if not needed.

Modifications in the underlying Iterable would lead to inconsistent cache. Removed cache completely.
Caches do not work for modifyable Iterables.

### CODE REVIEW

**Comment by 0crat** [comment]
@timmeey I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by Timmeey** [comment]
@yegor256 am i right in assuming that this IterableAsList should reflect changes in the underlying Iterable?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor try to merge

**Pull request merged**
