### PR TITLE
Merged ReplacedText and ReplacedRegexText

### PR DESCRIPTION
**Pull request by ixmanuel**
Reduced the quantity of objects.

### CODE REVIEW

**Comment by ixmanuel** [comment]
A better name could be ReplacedOccurrences, but we would have to change the rest of texts: Lowercased, Snakecased, Titlecased. Thus, I let it as ReplacedAllText instead of ReplacedText.

**Comment by ixmanuel** [comment]
@yegor256 A better name could be ReplacedOccurrences, but we would have to change the rest of texts in order to be consistent in the naming: Lowercased, Snakecased, Titlecased. Thus, I let it as ReplacedAllText instead of ReplacedText.

**Comment by yegor256** [comment]
@ixmanuel I don't really understand why do we need `RegexText`? Seems like something redundant to me.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#341` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#341](https://github.com/yegor256/cactoos/issues/341) was not in scope

**Pull request closed without merging**
