### PR TITLE
#413 add normal Mapped.toString()

### LINKED ISSUE #413: Mapped.toString() uses origin collection instead of mapped.
The following snippet prints `[1, 2, 3]`:

```java
System.out.println(
    new Mapped<>(
        Arrays.asList(1, 2, 3),
        x -> x*2
    ).toString()
);
```

Expected result is `[2, 4, 6]`

The issue affects all `Mapped`s that have suitable `toString` method (`list`, `collection` and `iterable`).

### PR DESCRIPTION
**Pull request by SharplEr**
Close #413

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#601](https://github.com/yegor256/cactoos/issues/601) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#601](https://github.com/yegor256/cactoos/issues/601) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by SharplEr** [comment]
@neonailol done, please take a look again.

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by neonailol** [comment]
@yegor256 please take a look at this

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+435](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9465](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#601](https://github.com/yegor256/cactoos/issues/601) is now out of scope

**Pull request merged**
