### PR TITLE
#399 : Implementing Unchecked IoChecked Bifunc 

### PR DESCRIPTION
**Pull request by memoyil**
Implementing Unchecked IoChecked Bifunc

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#404` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#404` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#404`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#404` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6035](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1260](http://www.0crat.com/u/kkamkou).

**Pull request merged**
