### PR TITLE
#600 fixing overflow error with int value

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Using BigDecimal for summation of values. Similar to `AvgOf` processing.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#602](https://github.com/yegor256/cactoos/issues/602) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#602](https://github.com/yegor256/cactoos/issues/602) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by svendiedrichsen** [comment]
@neonailol Done. Please verify.

**Comment by svendiedrichsen** [comment]
@neonailol I have added a test for a behaviour which the author of this bug was concerned about. I'm sorry. Could please review again. Thanks.

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by neonailol** [comment]
@yegor256 please take a look at this

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+465](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9510](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#602](https://github.com/yegor256/cactoos/issues/602) is now out of scope

**Pull request merged**
