### PR TITLE
(#1109) Make CollectionEnvelope.toString final and fix Mapped

### LINKED ISSUE #1109: CollectionEnvelope.java:42-44: Make the toString() method...
The puzzle `996-e264dc0b` from #996 has to be resolved: 

https://github.com/yegor256/cactoos/blob/f71ae47a514670e67ae3c8d9696f4f5070a97955/src/main/java/org/cactoos/collection/CollectionEnvelope.java#L42-L44

The puzzle was created by Victor Noël on 06-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by victornoel**
forgot to remove the `@todo` in #1130 that took care of #1109.

### CODE REVIEW

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @llorllale[/z](https://www.0crat.com/u/llorllale) please review this and merge or reject

**Comment by victornoel** [comment]
@llorllale can we merge this?

**Comment by llorllale** [comment]
@victornoel please remove GitHub keywords from the PR description

**Comment by victornoel** [comment]
@llorllale good point, sorry about that, it's done :)

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1136` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
