### PR TITLE
(#1183) Extracted Paged from IterableOf

### PR DESCRIPTION
**Pull request by ryoku**
This is for issue: #1183 

Extracted `Paged` from `IterableOf`
Added test for `Paged`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1273](https://github.com/yegor256/cactoos/issues/1273) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1273](https://github.com/yegor256/cactoos/issues/1273) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/27bc53b6-e4b3-4e60-82ad-e8e565925184); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@paulodamaso @victornoel What is the point of this paged iterable ????

**Comment by victornoel** [comment]
@fanifieiev I have no idea, it was there before but has no place in `IterableOf` so during refactoring, it was decided to move it out of `IterableOf`...

**Comment by fanifieiev** [comment]
> @fanifieiev I have no idea, it was there before but has no place in `IterableOf` so during refactoring, it was decided to move it out of `IterableOf`...

@victornoel I understand. I found the original ticket [971](https://github.com/yegor256/cactoos/issues/971) for that. Will go thru to understand it.
@

**Comment by fanifieiev** [comment]
@paulodamaso Please reject this PR as the DEV is not responding anymore.

**Comment by ryoku** [comment]
@paulodamaso, @fanifieiv please wait, I'll take care of this

**Comment by fanifieiev** [comment]
@ryoku This project has rules and policy.
The review should not take longer than 8 days, that is why REV can ask the ARC to reject PR.
Please read http://www.zerocracy.com/policy.html#55

**Comment by paulodamaso** [comment]
@ryoku please, go on

**Comment by paulodamaso** [comment]
@ryoku  It's taking too long, I'll close it

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (26 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Pull request [#1273](https://github.com/yegor256/cactoos/issues/1273) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@ryoku please make sure that problems found by the code reviewer would next time addressed by the pull request author (you)

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Pull request closed without merging**
