### PR TITLE
#460 MaxOf and MinOf with inner classes for primitive data types

### PR DESCRIPTION
**Pull request by bedward70**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#465` is in scope.

**Comment by yegor256** [comment]
@bedward70 don't you like how it's done in `SumOf`?

**Comment by yegor256** [comment]
@bedward70 I would rather implement `MinOf` and `MaxOf` similar to how `SumOf` works.

**Comment by bedward70** [comment]
Hi Yegor!
I tried to explain my point of view on the issue page:
https://github.com/yegor256/cactoos/issues/460

It will be OK, if the request is rejected.
The project rules are severe and I can't see any way to complete the issue.

**Comment by yegor256** [comment]
@bedward70 don't forget to start your messages with my name, otherwise I simply don't see them

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#465` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#465` is now out of scope.

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6270](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1500](http://www.0crat.com/u/kkamkou).

**Pull request closed without merging**
