### PR TITLE
RepeatedFuncTest does not test multiple runs #375

### PR DESCRIPTION
**Pull request by alex-semenyuk**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#383` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @alex-semenyuk, total is [+30](http://www.0crat.com/u/alex-semenyuk).

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#383` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#383`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#383` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#383` is not in scope

**Pull request merged**
