### PR TITLE
 #1466 Added titled

### PR DESCRIPTION
**Pull request by kokodyn**
Converts the text into titled case.
Added Title which is required to my other PR(Added Capitalized).

Signed-off-by: kokodyn <kokodyn@gmail.com>

### CODE REVIEW

**Comment by victornoel** [comment]
@kokodyn I'm a bit worried about the naming because from a user point of view, if I read the term `Titled`, I'm expecting the string to be transformed to a title, i.e. with the first character of each word being titled case. Do you have other idea to name this?

IMHO it would have been best to first merge the other PR #1465 with a `@todo` and then we could have taken the time to think about this problem.... maybe we need another abstraction for characters that shouldn't be confused with `Text`. It's not clear.

**Comment by victornoel** [comment]
@kokodyn I'm going to close this as #1465 is being merged. Also don't hesitate to join Zerocracy and this project if you want to contribute here and learn to use zerocracy :) see http://www.zerocracy.com/faq.html for details!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1474` is not assigned, can't get performer

**Comment by kokodyn** [comment]
@victornoel Thanks for invitation to "join Zerocracy" I will consider it :)

**Pull request closed without merging**
