### PR TITLE
172: Max and Min

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #172:

- `Max` introduced.
- `Min` introduced.

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
this Min/Max cannot handle empty lists/iterators

**Comment by fabriciofx** [comment]
@svendiedrichsen Thanks for your report. I think fixed them now. Could you check it?

**Comment by yegor256** [comment]
@rultor merge

**Comment by svendiedrichsen** [comment]
Tests are looking good. I was just thinking if the original NoSuchElementException isn't already good enough. WDYT?

**Comment by fabriciofx** [comment]
@svendiedrichsen Makes sense. I'll do it. Thanks!

**Pull request merged**
