### PR TITLE
(#1192) Using `iterator.Sliced` inside the `iterator.Skipped`

### PR DESCRIPTION
**Pull request by iakunin**
This is for https://github.com/yegor256/cactoos/issues/1192

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1202](https://github.com/yegor256/cactoos/issues/1202) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1202](https://github.com/yegor256/cactoos/issues/1202) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/775e1c89-6b50-4a83-9a34-f503b23bd4dc); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@iakunin please, fix the CI issues.

**Comment by iakunin** [comment]
@fabriciofx CI issues fixed

**Comment by iakunin** [comment]
@fabriciofx could you review this PR one more time, please?

**Comment by fabriciofx** [comment]
@iakunin @paulodamaso it seems fine to merge. Can do you do it?

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1202](https://github.com/yegor256/cactoos/issues/1202) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by sereshqua** [comment]
@fabriciofx please make sure that you will find at least 3 issues during next CR

**Comment by sereshqua** [comment]
@fabriciofx ping

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
