### PR TITLE
For #1396: Replace `MatcherAssert.assertThat` with `Assertion`

### PR DESCRIPTION
**Pull request by andreoss**
See #1396 

- All mentions of `MatcherAssert.assertThat` replaced with `Assertion` from `cactoos-matchers`
- `MatcherAssert` is banned by `forbidden-apis`

Apologies for a bulky diff. 
If it's not acceptable, we can go by adding a copy (see d77644b) and in-lining it package-by-package in several PRs.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1401](https://github.com/yegor256/cactoos/issues/1401) is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/06e4b04a-df4b-472a-9076-8c1d2020f5b4); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1401#issuecomment-648365781))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#1401](https://github.com/yegor256/cactoos/issues/1401), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#1401](https://github.com/yegor256/cactoos/issues/1401) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/083a9f9a-84ac-4c58-bb58-0f2770dae052); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@andreoss yes, this is problematic, because there are changes that are needed there and I think it would be best that as a REV, I can avoid spending 30mn reading this PR and writing comments. I would recommend keeping maybe the 10 first files, to get some feedbacks and avoid repeating the same mistakes everywhere.

That's why it is recommended to do smaller PRs: it will prevent you to waste your time correcting the same mistakes over and over. Also it could give the opportunity to other newcomers that starts with cactoos to work on simple tasks.

**Comment by victornoel** [comment]
@andreoss by the way do you realise that you are solving jobs that are not assigned to you and thus that you won't get points in zerocracy for them?

**Comment by andreoss** [comment]
@victornoel 
Technically the change was an easy one, I just have a method inlined by IDE (ece6633 c10ad65), going one-by-one would have taken more time for me. The trade-off here is reviewing of course.

**Comment by andreoss** [comment]
@victornoel Do you want me to limit changes to a single package? Are you okay with the keeping a copy (d77644b) of `hamcrest` class in order to easy refactoring (as proposed above) between RPs?

**Comment by victornoel** [comment]
@andreoss I don't really see the need for introducing this inlined method as you did. Simply replace `MatcherAssert` usage for a given package for example yes, and then modify the todo so that a new ticket is created by 0pdd.

**Comment by andreoss** [comment]
@victornoel The point of [the alias](https://refactoring.com/catalog/inlineFunction.html) is to make [the replacement](https://www.jetbrains.com/help/idea/inline.html) via IDE, rather than replacing by hand.

**Comment by victornoel** [comment]
@andreoss I understand that, it is a great idea for the dev working on the job, but it has no reason to transpire in the PR, that's all I'm saying. If you want to use that "tool", please do it, if you want to explain it in the todo for the next person working on this matter, don't hesitate, but I see no reason as a REV to see it present in the codebase that will be merged.

**Comment by victornoel** [comment]
@andreoss I'm closing this, don't hesitate to create new PRs that solve the todo iteratively and that creates new todo to continue the work.

**Comment by 0crat** [comment]
Code review was too long (9 days), architects (@paulodamaso, @victornoel[/z](https://www.0crat.com/u/victornoel)) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Pull request [#1401](https://github.com/yegor256/cactoos/issues/1401) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
