### PR TITLE
#378: ReaderOf, InputStreamOf, OutputStreamOf, etc.

### PR DESCRIPTION
**Pull request by yegor256**
see #378. Introduced these classes:

  * `OutputStreamTo`
  * `WriterAsOutput`
  * `WriterAsOutput`
  * `WriterAsOutputStream`
  * `WriterTo`
  * `ReaderOf`

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#379` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1080](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#379` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#379`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#379` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#379` is not in scope

**Pull request merged**
