### PR TITLE
#674: Add test case for "file" ctor of Directory

### PR DESCRIPTION
**Pull request by proshin-roman**
Pull request for issue #674: 
- renames input parameter of a ctor with file input parameter;
- adds a test case for this ctor.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#725](https://github.com/yegor256/cactoos/issues/725) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#725](https://github.com/yegor256/cactoos/issues/725) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/631927246). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by proshin-roman** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The issue is closed not by its creator, I won't close the order; please, re-open it and ask its creator to close it

**Comment by proshin-roman** [comment]
@yegor256 something strange has happened here with 0crat: it should assign the pull request to somebody for QA, but it doesn't.

**Comment by yegor256** [comment]
@0crat out

**Comment by yegor256** [comment]
@proshin-roman it was a bug: https://github.com/zerocracy/farm/issues/759

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @neonailol[/z](https://www.0crat.com/u/neonailol), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/725#issuecomment-371538399))

@yegor256 The job [#725](https://github.com/yegor256/cactoos/issues/725) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by elenavolokhova** [comment]
@neonailol According to our [QA rules](http://datum.zerocracy.com/pages/policy.html#42)
> The code reviewer found at least three problems in the code.

No issues were found during review.
Please, **confirm** that you'll try to find at least three design problems in next reviews.

**Comment by elenavolokhova** [comment]
@neonailol I need your confirmation in order to complete my review.

**Comment by neonailol** [comment]
@elenavolokhova i confirm

**Comment by elenavolokhova** [comment]
@neonailol Thanks! 
FYI: According to new rule in our policy:
>The quality of a job is “bad” if any of the following happens (these violations we can’t forgive):
The code reviewer didn’t find any issues in the pull request and just accepted it.

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
