### PR TITLE
(#1074) removed puzzle

### PR DESCRIPTION
**Pull request by longstone**
I've forgotten to remove the puzzle. This is done now.

### CODE REVIEW

**Comment by 0crat** [comment]
@longstone[/z](https://www.0crat.com/u/longstone) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @llorllale[/z](https://www.0crat.com/u/llorllale) please review this and merge or reject

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1083` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
