### PR TITLE
(#1199) Move some Bytes classes from io to bytes package

### PR DESCRIPTION
**Pull request by baudoliver7**
#1199
- Move Bytes classes from io to bytes package;
- Fix some errors of compilation in unit tests classes (there was some inner classes of io package that was required by some Bytes classes moved)
- Fix error about using static method Matchers.allOf in BytesOfTest

### CODE REVIEW

**Comment by baudoliver7** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1529#issuecomment-758495176))

@baudoliver7 This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1529](https://github.com/yegor256/cactoos/issues/1529) is [in scope](http://www.zerocracy.com/policy.html#14) for 10hr
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [10hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @baudoliver7[/z](https://www.0crat.com/u/baudoliver7): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231529%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1529#issuecomment-760245092))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1529](https://github.com/yegor256/cactoos/issues/1529), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1529](https://github.com/yegor256/cactoos/issues/1529); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by victornoel** [comment]
@baudoliver7 we are missing the class DigestEnvelope and its subclasses :) apart from that it looks good :)

**Comment by baudoliver7** [comment]
@victornoel Yes you are right. I moved them now. :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1529` is not assigned, can't get performer

**Pull request merged**
