### PR TITLE
Fix checkstyle for pr #516

### PR DESCRIPTION
**Pull request by iCok**
Fix checkstyle for pr #516

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#536` is now in scope, role is `REV`.

**Comment by 0crat** [comment]
This pull request [#536](https://github.com/yegor256/cactoos/issues/536) is assigned to [@fabriciofx](http://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and [§10](http://datum.zerocracy.com/pages/policy.html#10) and when you decide to accept the changes, inform [@yegor256](http://www.0crat.com/u/yegor256) right in this ticket.

**Comment by fabriciofx** [comment]
@yegor256 I accept review this PR.

**Comment by fabriciofx** [comment]
@yegor256 I accept the changes (this PR).

**Comment by fabriciofx** [comment]
@iCok Please, check why not this PR passed in the travis CI.

**Comment by yegor256** [comment]
@rultor merge

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/536#issuecomment-357551330))

@fabriciofx This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#536](https://github.com/yegor256/cactoos/issues/536) is in scope
  * The job is assigned to [@fabriciofx](http://www.0crat.com/u/fabriciofx)
  * These users are banned: [@icok](http://www.0crat.com/u/icok): This user reported the ticket

**Comment by iCok** [comment]
I was wrong making that pull request. Let's close it.

**Comment by 0crat** [comment]
The job [#536](https://github.com/yegor256/cactoos/issues/536) is now out of scope

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to [@fabriciofx](http://www.0crat.com/u/fabriciofx), total is [+180](http://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7345](http://www.0crat.com/u/yegor256)

**Pull request closed without merging**
