### PR TITLE
#54: Rename open() method in Input/Output interfaces

### PR DESCRIPTION
**Pull request by fabriciofx**
I renamed `Output` too, due the same reason of renamed `Input` interface.

### CODE REVIEW

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@rultor merge

**Comment by fabriciofx** [comment]
@yegor256 I resolved this conflict. Sould I delete the PR and send it again?

**Comment by yegor256** [comment]
@fabriciofx no, just push your changes to the same branch.

**Comment by fabriciofx** [comment]
@yegor256 Thanks for you attention! Could you check if its ok now?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by fabriciofx** [comment]
@yegor256 Could you try merge it again?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
