### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ashtonhogan**
If these principles change then the change should apply to all cactoos products

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#626](https://github.com/yegor256/cactoos/issues/626) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#626](https://github.com/yegor256/cactoos/issues/626) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/431842380). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@ashtonhogan Did you talk with @yegor256 about this change? It seems strange to me. Yegor invented Cactoos so, from my point of view, your repo should reference this repo's README, not the other way around :)

**Comment by ashtonhogan** [comment]
@amihaiemil I actually agree with you but @yegor256 doesn't like to talk too much, he prefers to just work with pull requests so I wasn't sure how to ask him to set up a new "cactoos-brand" repo?

**Comment by amihaiemil** [comment]
@yegor256 have a look here :)

**Comment by yegor256** [comment]
@ashtonhogan @amihaiemil looks like a nice shot, but I don't think we can call those principles "cactoos principles." They are more like EO principles, if you want to give them a name. And the best place to list them is here: elegantobjects.org. Cactoos is just a Java library that is designed to make Jave coding more object-oriented.

**Comment by ashtonhogan** [comment]
@amihaiemil @yegor256 I've added the principles to www.elegantobjects.org and updated this PR to point to www.elegantobjects.org instead of my github repo

**Comment by amihaiemil** [comment]
@ashtonhogan Where exactly, on elegantobjects.org, are the design principles listed? http://www.elegantobjects.org#principles points to no principle, at least I cannot find any on that pate :)

**Comment by amihaiemil** [comment]
@ashtonhogan ah, I see, the first paragraph... ok

**Comment by ashtonhogan** [comment]
@amihaiemil if you have necessary permissions, can you first approve this PR: https://github.com/yegor256/elegantobjects.github.io/pull/21

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@yegor256 what do we do with this one? Merge it, or?

**Comment by yegor256** [comment]
@amihaiemil I guess, we should. It does make sense... Not so many people will follow the link though, but keeping the list of "principles" in both places (here and in elegantobjects.org) is not a good idea too. WDYT?

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@yegor256 don't forget about this one. I saw the PR for elegantobjects.org was merged already.

**Comment by amihaiemil** [comment]
@ashtonhogan there's a conflict now, can you fix it?

**Comment by amihaiemil** [comment]
@ashtonhogan ping

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@yegor256 ping; can we merge this?

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@ashtonhogan According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please provide a link to original issue in PR's description.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews. If the PR is too small it should be combined with other related issue and fixed. It would be a high quality ticket.

**Comment by ashtonhogan** [comment]
I'm confused, this is already closed?

**Comment by amihaiemil** [comment]
@ashtonhogan yes, it is, but please do as the QA asks :)

**Comment by amihaiemil** [comment]
@ypshenychka I confirm I'll try to find more bugs

**Comment by ypshenychka** [comment]
@ashtonhogan Payments are not made until QA review is completed. So please consider the [comment](https://github.com/yegor256/cactoos/pull/626#issuecomment-366807374) above.

And also pay attention that according to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your [message](https://github.com/yegor256/cactoos/pull/626#issuecomment-366814250) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@amihaiemil Thank you.

**Comment by ashtonhogan** [comment]
@ypshenychka okay I've added the link in the description

**Comment by ypshenychka** [comment]
@ashtonhogan Thanks.

**Comment by ypshenychka** [comment]
@0crat Quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+315](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+790](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10334](https://www.0crat.com/u/yegor256)

**Pull request merged**
