### PR TITLE
#599 fix javadocs and test name

### LINKED ISSUE #599: Wrong count files in Directory
org.cactoos.io.DirectoryTest:

```
   @Test
    public void listsFilesInDirectory() throws IOException {
        final Path dir = Files.createTempDirectory("x1");
        dir.resolve("x/y").toFile().mkdirs();
        Files.write(dir.resolve("x/y/test"), "".getBytes());
        MatcherAssert.assertThat(
            "Can't list files in a directory",
            new Directory(dir),
            // @checkstyle MagicNumber (1 line)
            Matchers.iterableWithSize(4)
        );
    }

```

Actually in this test only one file is created, not 4. `Files.walk` from org.cactoos.io.Directory#iterator includes sub directories in this count.

### PR DESCRIPTION
**Pull request by SharplEr**
#599

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#628](https://github.com/yegor256/cactoos/issues/628) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#628](https://github.com/yegor256/cactoos/issues/628) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/432004623). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@SharplEr looks ok. Just please, change the PRs decription. Remove the keyword "Closes" (we don't want the ticket to be closed automatically after this is merged; the initial author has to aprove the solution and close the ticket).

**Comment by amihaiemil** [comment]
@SharplEr ping

**Comment by amihaiemil** [comment]
@SharplEr ping

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by SharplEr** [comment]
@amihaiemil  Sorry, I was busy) I fixed the description.

**Comment by amihaiemil** [comment]
@yegor256 we can merge this now

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@ypshenychka Can you give the verdict here? I have a lot of tasks already (over 20) and can't keep track of them anymore easily.

**Comment by ypshenychka** [comment]
@amihaiemil Don't worry. I will review this ticket once issue https://github.com/zerocracy/farm/issues/592 is resolved.

**Comment by ypshenychka** [comment]
@SharplEr Please provide informative description so that we know what was done in scope of this PR. Just a link to initial issue is not enough.

**Comment by ypshenychka** [comment]
@SharplEr @amihaiemil FYI - I'll be able to finish QA review only after my remark is considered.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.
>Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. Please confirm that you'll try to find at least three problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka yes, I will try to find more issues next time.

@SharplEr don't forget to address the QA's comment regarding the description

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@SharplEr can you pls update the description as required by the QA? Thanks.

**Comment by amihaiemil** [comment]
@SharplEr ping

**Comment by amihaiemil** [comment]
@SharplEr ping

**Comment by ypshenychka** [comment]
@SharplEr Could you please consider my [remark](https://github.com/yegor256/cactoos/pull/628#issuecomment-366797554) and make corresponding chanes?

**Comment by amihaiemil** [comment]
@SharplEr can you also fix it here? :D

**Comment by amihaiemil** [comment]
@ypshenychka Author fixed description here as well :)

**Comment by SharplEr** [comment]
@amihaiemil @ypshenychka Done)
BTW
It's real hard to find a lot of problems in such simple PR.

**Comment by amihaiemil** [comment]
@SharplEr yes, there is an issue about it, these kind of PRs should skip CR: https://github.com/zerocracy/farm/issues/510

**Comment by amihaiemil** [comment]
@ypshenychka ping, can you give the verdict? I have this task already for 10days, 0crat could take it away any minute :D

**Comment by 0crat** [comment]
The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#628](https://github.com/yegor256/cactoos/issues/628), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+905](https://www.0crat.com/u/amihaiemil)

**Comment by ypshenychka** [comment]
@amihaiemil sorry, was not online. I wish @SharplEr made his changes earlier.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/628#issuecomment-367820251))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Crypto[144] java.io.IOException: Failed to buy at Coinbase
com.coinbase.api.CoinbaseImpl[1330] com.coinbase.api.exception.CoinbaseException: Your account has been locked, please visit coinbase.com to resolve
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/628#issuecomment-367820251))

@ypshenychka Job `gh:yegor256/cactoos#628` is not assigned, can't get start time

**Comment by 0crat** [comment]
`QA` review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+570](https://www.0crat.com/u/ypshenychka)

**Comment by amihaiemil** [comment]
@ypshenychka no prob, happens :)

**Comment by 0crat** [comment]
This pull request [#628](https://github.com/yegor256/cactoos/issues/628) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/591755016). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by neonailol** [comment]
@yegor256 this job was assigned to me by mistake

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/628#issuecomment-370395947))

@yegor256 @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#628](https://github.com/yegor256/cactoos/issues/628), since the job is not in scope anymore

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/628#issuecomment-370395947))

@yegor256 The job [#628](https://github.com/yegor256/cactoos/issues/628) is now out of scope

**Pull request merged**
