### PR TITLE
#872 Iso class implement Scalar

### PR DESCRIPTION
**Pull request by DanielPalafox**
Implement Scalar in Iso class for #872

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#931](https://github.com/yegor256/cactoos/issues/931) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#931` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#931](https://github.com/yegor256/cactoos/issues/931) is now out of scope

**Pull request merged**
