### PR TITLE
#1413: Let's remove non-decorator from list package

### PR DESCRIPTION
**Pull request by fabriciofx**
Per #1413 

- Remove classes `list.Sorted`, `list.Shuffled` and `list.Mapped`
- Remove repective tests classes

### CODE REVIEW

**Review by andreoss — APPROVED** [review]
@victornoel Looks fine

**Comment by victornoel** [comment]
@andreoss thx, indeed nothing much to review there :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @andreoss[/z](https://www.0crat.com/u/andreoss)[/z](https://www.0crat.com/u/andreoss) didn't make CR comments

**Pull request merged**
