### PR TITLE
Array as list

### PR DESCRIPTION
**Pull request by englishman**
replace `Arrays.asList` calls with `ArrayAsList` class for #62

### CODE REVIEW

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@englishman we already have `ArrayAsIterable` and `IterableAsList`. We can combine them. No need to create a new class.

**Comment by englishman** [comment]
@yegor256 Ahhh... I see but...
```
new ArrayAsList<>("hello", "world")
```
looks more convenient than
```
new IterableAsList(new ArrayAsIterable<>("hello", "world"))
```
WDYT?

**Comment by yegor256** [comment]
@englishman you can add a new ctor to `IterableAsList`, which will accept an array and call `new ArrayAsIterable`

**Comment by englishman** [comment]
@yegor256 agree. Raised #149. This PR can be closed

**Pull request closed without merging**
