### PR TITLE
1479 | fix previous typo

### PR DESCRIPTION
**Pull request by mtadmk**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed
  - Title begins with the issue's number, then a short title
  - Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
  - Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).
  - You ran the build locally and it passed (see .travis.yml for all checks performed on PRs)

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by 0crat** [comment]
@mtadmk[/z](https://www.0crat.com/u/mtadmk) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @victornoel[/z](https://www.0crat.com/u/victornoel) please review this and merge or reject

**Comment by victornoel** [comment]
@mtadmk many thanks for the contribution, would you consider joining zerocracy and the cactoos project there and participate actively as a developer and reviewer? :)
You can find more details there: http://www.zerocracy.com/faq.html

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1483` is not assigned, can't get performer

**Pull request merged**
