### PR TITLE
#608 Removed code duplication of Reversed

### PR DESCRIPTION
**Pull request by nick318**
#608 Removed code duplication of `iterable/Reversed` and `collection/Reversed`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#649](https://github.com/yegor256/cactoos/issues/649) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#649](https://github.com/yegor256/cactoos/issues/649) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/460923201). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@nick318 Looks ok; I assume there are already some unit test for this class, right?

**Comment by nick318** [comment]
@amihaiemil right, it is fully covered.

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by nick318** [comment]
@yegor256 take a look, please

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+75](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+675](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10054](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/649#issuecomment-366642354))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#649](https://github.com/yegor256/cactoos/issues/649) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23649%27%7D) (restricted area)

**Pull request merged**
