### PR TITLE
TextOf brevity#274 - In sync with InputOf and BytesOf

### PR DESCRIPTION
**Pull request by ixmanuel**
@yegor256 TextOf ready. 
### Key notes:
1. I had to change the main ctor. of BytesOf to public.
2. What do you think about integrating ThrowableAsBytes to BytesOf and TextOf.
3. If we change ReaderAsInput to ReaderAsBytes we could integrate it to InputOf, BytesOf and TextOf.

### CODE REVIEW

**Comment by ixmanuel** [comment]
@yegor256 Well, I had some issues with the default encoding in windows (I guess it is in UTF-16). But now the tests are ok.

1. The main ctor. of BytesOf remains private.
2. What do you think about integrating ThrowableAsBytes to BytesOf and TextOf.
3. If we change ReaderAsInput to ReaderAsBytes we could integrate it to InputOf, BytesOf and TextOf.

**Comment by yegor256** [comment]
> The main ctor. of BytesOf remains private.

Cool.

> What do you think about integrating ThrowableAsBytes to BytesOf and TextOf.

Totally agree.

> If we change ReaderAsInput to ReaderAsBytes we could integrate it to InputOf, BytesOf and TextOf.

Agree.

**Comment by yegor256** [comment]
@ixmanuel many thanks for your contribution!

**Comment by ixmanuel** [comment]
I'm happy  to work with you guys. Thanks for sharing and I think TextOf is ready :) @yegor256

**Comment by memoyil** [comment]
@ixmanuel Nice one thank you. This would be great for users.

**Comment by memoyil** [comment]
@ixmanuel  Will we remove "*AsText" classes ?

**Comment by ixmanuel** [comment]
@memoyil: Yes, they are gone.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
