### PR TITLE
(#1180) Made README.md examples compilable

### PR DESCRIPTION
**Pull request by emfataliev**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1181](https://github.com/yegor256/cactoos/issues/1181) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1181](https://github.com/yegor256/cactoos/issues/1181) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/6fe0649a-ed7b-4b27-85ef-d1f32d477dab); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
Code review was too long (8 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#1181](https://github.com/yegor256/cactoos/issues/1181) is now out of scope

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1181` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
