### PR TITLE
#30 Predication

### PR DESCRIPTION
**Pull request by VsSekorin**
As per https://github.com/yegor256/cactoos/issues/30
`Func.Pred` introduced

### CODE REVIEW

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@VsSekorin thanks!

**Pull request merged**
