### PR TITLE
#372 : Polish Scalar Package

### PR DESCRIPTION
**Pull request by memoyil**
Polishing Scalar Package

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#373` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @memoyil, total is [+15](http://www.0crat.com/u/memoyil).

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#373` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#373`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#373` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#373` is not in scope

**Pull request merged**
