### PR TITLE
#803 added iterator of booleans and chars

### PR DESCRIPTION
**Pull request by krzyk**
#803 
- added `IteratorOfBooleans` and `IteratorOfChars` and used them in appropriate IterablesOf
- added tests for those
- added todo to implement similar iterators for bytes and doubles

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#831](https://github.com/yegor256/cactoos/issues/831) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#831](https://github.com/yegor256/cactoos/issues/831) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1272048483); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by krzyk** [comment]
@Vatavuk updated, please see again

**Comment by Vatavuk** [comment]
@llorllale good to merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#831](https://github.com/yegor256/cactoos/issues/831) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +20 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
