### PR TITLE
#897, classes implementing Text were refactored to extend TextEnvelope in package org.cactoos.time

### PR DESCRIPTION
**Pull request by butenkos**
this is for #897 

- all classes implementing `Text` were refactored to extend `TextEnvelope` in package `org.cactoos.time`
- unit tests have been adjusted in accordance with changes to classes implementing Text in package org.cactoos.time
- new puzzle has been created

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#921](https://github.com/yegor256/cactoos/issues/921) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#921](https://github.com/yegor256/cactoos/issues/921) is assigned to @vssekorin[/z](https://www.0crat.com/u/vssekorin), here is [why](https://www.0crat.com/footprint/C63314D6Z/1852157608); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by butenkos** [comment]
@VsSekorin kind reminder

**Comment by VsSekorin** [comment]
@rultor good to merge

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vssekorin[/z](https://www.0crat.com/u/vssekorin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#921](https://github.com/yegor256/cactoos/issues/921) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
