### PR TITLE
#610 Refactor static methods in TeeInputStreamTest and TeeOutputStrea…

### PR DESCRIPTION
**Pull request by flslkxtc**
#610. TeeOutputStreamTest and TeeInputStreamTest tests refactoring: replace static methods #asString() with TextOf objects.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#624](https://github.com/yegor256/cactoos/issues/624) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#624](https://github.com/yegor256/cactoos/issues/624) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/431804305). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@flslkxtc It looks ok. Just please, reference the main ticket in the PR's description and write a few words about the changes. For instance: "As per #610. Refactored to use TextOf#asString() and removed static methods #asString"

**Comment by flslkxtc** [comment]
@amihaiemil thank you, i've updated this pull request description.

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+600](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9709](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#624](https://github.com/yegor256/cactoos/issues/624) is now out of scope

**Pull request merged**
