### PR TITLE
#1508 Joined(items, item) ctor is missing

### PR DESCRIPTION
**Pull request by ainGitHub**
Add ctor and test

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed
  - Title begins with the issue's number, then a short title
  - Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
  - Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).
  - You ran the build locally and it passed (see .travis.yml for all checks performed on PRs)

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by victornoel** [comment]
@ainGitHub thank you for your contribution; Could you fix the one failing check?

**Comment by 0crat** [comment]
Job [#1523](https://github.com/yegor256/cactoos/issues/1523) is already in scope

**Comment by 0crat** [comment]
GitHub issue is still open, won't close

**Comment by ainGitHub** [comment]
> @ainGitHub thank you for your contribution; Could you fix the one failing check?

Fix failing check. What codestyle used in project? Ideas default code formatting not accept qulice checks

**Comment by victornoel** [comment]
@ainGitHub we use qulice and unfortunately, apart from the maven plugin logs, there is nothing else to get feedback. But I see you managed to fix the linting, so it should be ok I guess.

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1523#issuecomment-755677930))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1523](https://github.com/yegor256/cactoos/issues/1523) is [in scope](http://www.zerocracy.com/policy.html#14) for 10hr
  * The role is `REV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [10hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @aingithub[/z](https://www.0crat.com/u/aingithub): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231523%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/cactoos/issues/1523#issuecomment-756092852))

@sereshqua There is no quality review for [#1523](https://github.com/yegor256/cactoos/issues/1523), no performer

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
