### PR TITLE
#686: Add more tests for OutputTo

### PR DESCRIPTION
**Pull request by proshin-roman**
Pull request for issue #686. It covers all ctors of the OutputTo class by tests.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#745](https://github.com/yegor256/cactoos/issues/745) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#745](https://github.com/yegor256/cactoos/issues/745) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/811247855); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by proshin-roman** [comment]
@fabriciofx could you review the pull request, please?

**Comment by proshin-roman** [comment]
@fabriciofx ping

**Comment by proshin-roman** [comment]
@fabriciofx ping

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@fabriciofx ping

**Comment by proshin-roman** [comment]
@fabriciofx Could you review this pull request, please?

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#745](https://github.com/yegor256/cactoos/issues/745), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
This pull request [#745](https://github.com/yegor256/cactoos/issues/745) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/911278594); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by proshin-roman** [comment]
@neonailol Could you review this pull request, please?

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @neonailol[/z](https://www.0crat.com/u/neonailol), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#745](https://github.com/yegor256/cactoos/issues/745) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by elenavolokhova** [comment]
@neonailol According to our Policy:
>The code reviewer found at least three problems in the code

No issues were found by you in this case. 
Please, confirm that you will try to find at least three problems next time.

**Comment by proshin-roman** [comment]
@neonailol The pull request still needs your attention - please check last comments.

**Comment by elenavolokhova** [comment]
@neonailol Please, respond to my comment. I can not complete QA review without your confirmation.

**Comment by proshin-roman** [comment]
@yegor256 It looks like a bug that this issue is still assigned to the reviewer as he doesn't respond to the question more than 6 days. Is it possible to do something with this ticket?

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by elenavolokhova** [comment]
@0crat status

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/745#issuecomment-382015853))

@elenavolokhova This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#745](https://github.com/yegor256/cactoos/issues/745) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23745%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by proshin-roman** [comment]
@yegor256 Could you look at this pull request and related ticket, please? Something goes wrong as the pull request has been reviewed but the ticket is still not closed.

**Comment by yegor256** [comment]
@proshin-roman which ticket? Please, ask the question where it belongs.

**Pull request merged**
