### PR TITLE
#366 : Base64 Encoded Text Implementation

### PR DESCRIPTION
**Pull request by memoyil**
Base64EncodedText Impl

### CODE REVIEW

**Comment by yegor256** [comment]
@memoyil I think that we don't need these Encoded/Decoded classes in Cactoos. Simply because they are very simple and don't really add anything to the existing JDK methods. Moreover, with lambda in Java8 it's very easy to create one on-fly.

**Comment by memoyil** [comment]
@yegor256 Ok. I will close this issue and open a new one to delete the decoded one.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-04T07:36:32
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:197)
	at com.zerocracy.farm.reactive.RunnableWithTrigger.run(RunnableWithTrigger.java:52)
	at java....
```

**Comment by memoyil** [comment]
@yegor256  It is already deleted. Nothing to do.

**Pull request closed without merging**
