### PR TITLE
#27 TextAsBytes with test

### PR DESCRIPTION
**Pull request by VsSekorin**
As per https://github.com/yegor256/cactoos/issues/27

`TextAsBytes` introduced

### CODE REVIEW

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin I'm not sure we need a separate package for that. Can you imagine what other classes we will put there?

**Comment by VsSekorin** [comment]
@yegor256 I assumed that there will be some classes that implements Bytes, for example InputAsBytes. But if this happens very rarely, then you're completely right.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@VsSekorin thanks!

**Pull request merged**
