### PR TITLE
change external test resource to file system file

### PR DESCRIPTION
**Pull request by englishman**
Fix tests for #151

### CODE REVIEW

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
@englishman I think its better use Takes to running a https server and provide a file to be retrieved, similar to [here](https://github.com/yegor256/cactoos/blob/master/src/test/java/org/cactoos/io/UrlAsInputTest.java#L59-L77). WDYT?

**Comment by englishman** [comment]
@fabriciofx I don't think it's an option as `FtRemote.Script` impl gives to test code `URI` but problem situation requires `String` and `URI` instance is created from string in a classes under the test.

Honestly, I don't understand why Take framework was used even in your example as it looks like an attempt to test also an JDK `URL` class we actually don't need.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
