### PR TITLE
(#1618) MapOf(map, X, Y) and MapOf(X, Y) new ctors

### PR DESCRIPTION
**Pull request by evpl**
For issue #1618 

Added new constructors:
* `MapOf(map, X, Y)`
* `MapOf(X, Y)`

And tests

### CODE REVIEW

**Review by victornoel — CHANGES_REQUESTED** [review]
@evpl hi, thanks for the contribution, could you also update the javadoc of the class, as explained in the ticket: it does not reflect the behaviour of the class. Thx!

**Comment by evpl** [comment]
@victornoel hi, I fixed the javadoc.

**Comment by victornoel** [comment]
@evpl perfect :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1625#issuecomment-917606180))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1625](https://github.com/yegor256/cactoos/issues/1625) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `REV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @evpl[/z](https://www.0crat.com/u/evpl): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231625%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat out

**Comment by victornoel** [comment]
@0crat out

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1625#issuecomment-917643382))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1625](https://github.com/yegor256/cactoos/issues/1625) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `REV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @evpl[/z](https://www.0crat.com/u/evpl): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231625%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/1625#issuecomment-917638373))

@victornoel Job [#1625](https://github.com/yegor256/cactoos/issues/1625) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/1625#issuecomment-917638373))

@victornoel Job [#1625](https://github.com/yegor256/cactoos/issues/1625) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
