### PR TITLE
#154: BooleanAsScalar, IntegerAsScalar, LongAsScalar, FloatAsScalar and DoubleAsScalar

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #154:

- `BooleanAsScalar` introduced
- `IntegerAsScalar` introduced
- `LongAsScalar` introduced
- `FloatAsScalar` introduced
- `DoubleAsScalar` introduced

### CODE REVIEW

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@fabriciofx good idea, but I think you got the names wrong :) Must be `BooleanAsScalar`, etc.

**Comment by fabriciofx** [comment]
@yegor256 You're right! I'll fix it. Thanks!

**Comment by fabriciofx** [comment]
@yegor256 Apparently we have some problem wit `StickyInputTest`. Could you check it?
```
[ERROR] /home/travis/build/yegor256/cactoos/src/test/java/org/cactoos/io/StickyInputTest.java:[46,33] incompatible types: cannot infer type-variable(s) T,X,Y
    (argument mismatch; org.cactoos.func.RepeatedFunc<org.cactoos.io.StickyInput,Y> cannot be converted to org.cactoos.Func<org.cactoos.io.StickyInput,java.lang.Boolean>)
```

**Comment by yegor256** [comment]
@fabriciofx please, submit a separate ticket about that

**Comment by yegor256** [comment]
@fabriciofx look, I can't really understand the benefit of this. Now I can do:

```
Scalar<Double> s = () -> 1.5d;
```

You're suggesting:

```
Scalar<Double> s = new DoubleAsScalar(1.5d);
```

What is the difference? The second option is even longer.

**Comment by fabriciofx** [comment]
@yegor256 I'm sorry, but I didn't know if it's possible. I need to improve my lambda knowledge. 😄 I'll close this PR.

**Pull request closed without merging**
