### PR TITLE
(#930) Homogeneous constructor parameters for iter

### PR DESCRIPTION
**Pull request by victornoel**
This is for #930.

While I was at it, I took care of the parameter order of Synced too and I updated the tests modified to use `Assertion`.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1092](https://github.com/yegor256/cactoos/issues/1092) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1092](https://github.com/yegor256/cactoos/issues/1092) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/06e79afa-2526-44b3-9046-db833ef42dd7); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale 0crat did it again and assigned my PR to myself

**Comment by victornoel** [comment]
@llorllale I've noticed `ItemAt` has the iterable/iterator first in the constructor, should I add a `@todo` so that it is last as in here?

**Comment by llorllale** [comment]
@victornoel go ahead

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1092#issuecomment-478801175))

@llorllale The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1092](https://github.com/yegor256/cactoos/issues/1092), please stop working. Reason for job resignation: Order was cancelled

**Comment by victornoel** [comment]
@llorllale done

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1092` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1092](https://github.com/yegor256/cactoos/issues/1092) is now out of scope

**Pull request merged**
