### PR TITLE
(#0000) Contibuters readme update

### PR DESCRIPTION
**Pull request by fanifieiev**
This small PR is just to update the list of contributers with new people not currently listed there.

### CODE REVIEW

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1312` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Pull request merged**
