### PR TITLE
(#1170, #895) Refactor FallbackFrom and simplify ScalarWithFallback

### PR DESCRIPTION
**Pull request by baudoliver7**
#1170, #895

- Refactor FallbackFrom by introducing a new interface
- Declare Fallback interface in ScalarWithFallback

### CODE REVIEW

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Pull request [#1524](https://github.com/yegor256/cactoos/issues/1524) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request closed without merging**
