### PR TITLE
Add BytesAsInput

### PR DESCRIPTION
**Pull request by VsSekorin**

### CODE REVIEW

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin how about a unit test? How you know that the code works?

**Comment by VsSekorin** [comment]
@yegor256 My mistake. Test added.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@VsSekorin `InputAsText` is gone, you should use `new BytesAsText(new InputAsBytes(...))`

**Pull request closed without merging**
