### PR TITLE
Add constructors using Texts to ResourceOf

### PR DESCRIPTION
**Pull request by aliceice**
As per #558

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#562](https://github.com/yegor256/cactoos/issues/562) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#562](https://github.com/yegor256/cactoos/issues/562) is assigned to @amihaiemil[/z](http://www.0crat.com/u/amihaiemil). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](http://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@aliceice I will look over this today, but keep in mind that generally it is not ok for the bug submitter to also fix it :) First of all, that ticket was not assigned to you, so you won't be paid. You could ask Yegor to asign that task to you.

**Comment by aliceice** [comment]
@amihaiemil I'm not even a project member. I am just using this fine library of objects in one of my projects and wanted to help out (no payment needed). Sorry if I did something wrong!

**Comment by amihaiemil** [comment]
@aliceice No, it's ok :) I thought you were a new member. I see you are pretty accustomed with Yegor's style of development, so you should apply in 0crat.com, after the beta testing is done (even now if you want, but we're testing the system, it has a lot of bugs still).

**Comment by amihaiemil** [comment]
@aliceice Anyway, the PR looks good, just one notice:

inside method ``stream()``, this.input and this.path are used; those used to be CharSequence, simple Strings, now they are of type Text, so I think you should call ``.asString()``, to make sure it will work.

As I saw, the ``Text`` implementations you used in the tests are overriding ``toString()``, so the tests are fine, but maybe a future implementation of ``Text`` will not override it? -- yeah, it's not clear to me why ``Text`` has ``asString()`` in the first place, when it could make use of ``toString`` all the time.

**Comment by aliceice** [comment]
@amihaiemil Thanks for the hint with 0crat.com. I'm eagerly awaiting the end of the beta test :)

You are right about the `stream()` method! I'll quickly add them so it is safe to use them with any `Text`.

I think `Text` has `asString()` as `toString()` does not allow to throw checked exceptions as it's just inherited from `Object`.

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@yegor256 ping, don't forget about this one

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+45](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7805](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#562](https://github.com/yegor256/cactoos/issues/562) is now out of scope

**Pull request merged**
