### PR TITLE
#377 ItemAt has duplicate

### PR DESCRIPTION
**Pull request by nikialeksey**
Merged ItemAt into one class

Issue https://github.com/yegor256/cactoos/issues/377

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#604](https://github.com/yegor256/cactoos/issues/604) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#604](https://github.com/yegor256/cactoos/issues/604) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by nikialeksey** [comment]
This may be changed like:
```java
this(new StickyScalar<>(source::iterator), position, fallback);
this(new StickyScalar<>(() -> iterator), position, fallback);
```

**Comment by neonailol** [comment]
@yegor256 please take a look at this

**Comment by yegor256** [comment]
@nikialeksey @neonailol indeed, type casting is a bad idea in OOP, let's not use it: http://www.yegor256.com/2015/04/02/class-casting-is-anti-pattern.html

**Comment by nikialeksey** [comment]
@neonailol [Done](https://github.com/yegor256/cactoos/pull/604/commits/da8fc2a5c10bbf32125075b98269c83d0738fd54)

**Comment by neonailol** [comment]
@yegor256 it is not technically a type casting for this case, it's more like helper for java compilation, so it can understand type correctly, if there was a class ScalarOf like i have in [here](https://github.com/neonailol/kactoos/blob/99c52844696edfb0e23d4bfd59e2ec709039ce36/kactoos-common/src/main/kotlin/nnl/rocks/kactoos/scalar/ScalarOf.kt) it would be the same as this cast

**Comment by neonailol** [comment]
@rultor goot to merge

**Comment by nikialeksey** [comment]
@yegor256 Please confirm this

**Comment by yegor256** [comment]
@rultor merge

**Comment by nikialeksey** [comment]
@yegor256 please try again

**Comment by neonailol** [comment]
@yegor256 please take a look at this

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+390](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9435](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#604](https://github.com/yegor256/cactoos/issues/604) is now out of scope

**Pull request merged**
