### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by janczer**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#517` is now in scope.

**Comment by yegor256** [comment]
@janczer thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#517` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#517` is now out of scope.

**Pull request merged**
