### PR TITLE
Moved nested NoNulls scalar class into its own NoNullsScalar class

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#484` is in scope.

**Comment by yegor256** [comment]
@ashtonhogan what for? See the discussion in #209

**Comment by ashtonhogan** [comment]
@yegor256 I read the conversation, it contains many good points. I see that you have reached a conclusion historically already. My reason for doing this is that I think it tightly couples NoNull to other classes and makes it difficult to remember and even more difficult for a new user to understand.

Should classes ever be nested? Assuming no static...

1. public/protected nested class: Either migrate it to the parent class or move it into its own class. Why would a famous celebrity live in their mothers basement? This is being used publicly, it should be independent and make its own rules

2. private nested class: I guess you could use this to organise some of your methods but I can't think of any good reason to use it... Just makes your class look less standardised and requires more effort to read imo

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#484` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by yegor256** [comment]
@ashtonhogan good questions, but they are off-topic here. We won't move these classes out, they will stay inside :) Please, feel free to submit new tickets with the questions you raised.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#484` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1590](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6330](http://www.0crat.com/u/yegor256).

**Pull request closed without merging**
