### PR TITLE
(#1242) ListOf is now a concrete in-memory List implementation

### PR DESCRIPTION
**Pull request by victornoel**
This is for #1242.

As per discussed with ARC in #1242:
- I reimplemented `ListOf` to be a normal `List` implementation (based on `LinkedList`)
- Removed meaningless `List` decorators because of that and adjusted tests
- Added `@todo`s for continuing the work
  - Removing any class from `collection` package that can be replaced by `Iterable` based ones or other concrete implementation from packages `list` or `set`
  - Implementing `SetOf` in the same way

Unfortunately, I had to modify an existing todo (#1233) for the build not to fail but it should be alright as it is not currently assigned (well it is, but by someone that did nothing for 6 months...).

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1290](https://github.com/yegor256/cactoos/issues/1290) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/6d951a36-6bfe-4435-956c-5561e729f77c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@victornoel Why is `ListOf` is based on `LinkedList `rather than on `ArrayList `?
Was there any pros & cons discussed?

**Comment by victornoel** [comment]
> @victornoel Why is `ListOf` based on `LinkedList `rather than on `ArrayList `?
> Was there any pros & cons discussed?

@fanifieiev why not? if you have some concerns, let's discuss them now or with ARC but I don't think it is really important IMHO.

**Comment by fanifieiev** [comment]
> > @victornoel Why is `ListOf` based on `LinkedList `rather than on `ArrayList `?
> > Was there any pros & cons discussed?
> 
> @fanifieiev why not? if you have some concerns, let's discuss them now or with ARC but I don't think it is really important IMHO.

@victornoel I agree, but I have one concern that is worth discussing.
Mutable list implementations might be based on `LinkedList`, but immutable lists(if we have them) should be better based on `ArraysList`.
So based on this, IMHO, we need to be selective when we need to build mutable or immutable.

**Comment by victornoel** [comment]
@fanifieiev 

> Mutable list implementations might be based on `LinkedList`, but immutable lists(if we have them) should be better based on `ArraysList`.

A few points from my pov:
- `List` is mutable by contract, `ListOf` just follows this contract, so it is ok to consider it should be mutable
- If you need an immutable list, are you sure you need an instance of `List` or maybe you need some other interface (see for examples those provided in eclipse-collections)
- If a user needs a specific implementation of list, he can just use it, as long as they implement `List`, `ListOf` is here mostly as an easy to use `List` implementation with a nice constructor. IMHO cactoos should provide interesting List decorators, but implementations? Not so much, or at least not for now (see point 2 in https://github.com/yegor256/cactoos/issues/1242#issuecomment-561945766)
- for readers not aware of this: we should be careful about the term "immutable", for example we have an immutable decorator which is different from an immutable datastructure!

So IMHO, all of this discussion is out of scope of this PR, instead it would be better to raise new issues to tackle them.

**Comment by fanifieiev** [comment]
> @fanifieiev
> 
> > Mutable list implementations might be based on `LinkedList`, but immutable lists(if we have them) should be better based on `ArraysList`.
> 
> A few points from my pov:
> 
> * `List` is mutable by contract, `ListOf` just follows this contract, so it is ok to consider it should be mutable
> * If you need an immutable list, are you sure you need an instance of `List` or maybe you need some other interface (see for examples those provided in eclipse-collections)
> * If a user needs a specific implementation of list, he can just use it, as long as they implement `List`, `ListOf` is here mostly as an easy to use `List` implementation with a nice constructor. IMHO cactoos should provide interesting List decorators, but implementations? Not so much, or at least not for now (see point 2 in [#1242 (comment)](https://github.com/yegor256/cactoos/issues/1242#issuecomment-561945766))
> * for readers not aware of this: we should be careful about the term "immutable", for example we have an immutable decorator which is different from an immutable datastructure!
> 
> So IMHO, all of this discussion is out of scope of this PR, instead it would be better to raise new issues to tackle them.

@victornoel ok, I agree with with you.

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@fanifieiev please make sure you will try to find at least 3 issues during next CR, thanks

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by fanifieiev** [comment]
> @fanifieiev please make sure you will try to find at least 3 issues during next CR, thanks

@sereshqua Ok, will do that.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Pull request merged**
