### PR TITLE
(#1567) Generify `org.cactoos.proc` package

### PR DESCRIPTION
**Pull request by DmitryBarskov**
For #1567:

Generify incoming parameters (use `? super T`) for next classes:
- `ProcOf`, `ProcEnvelope` and `FuncOf`
- `ProcNoNulls`
- `BiProcOf` and `BiProcEnvelope`
- `BiProcNoNulls`
- `RepeatedProc` and `Repeated`

### CODE REVIEW

**Review by andreoss — APPROVED** [review]
j

**Review by victornoel — CHANGES_REQUESTED** [review]
@DmitryBarskov please update the todo (change the ticket number at the beginning with the one you just did) or maybe you are planning to do more PRs? As long as the todo is in the code base, it means it's not done and if it's not done, it is still assigned to the same person (you ;)

**Review by victornoel — CHANGES_REQUESTED** [review]
@DmitryBarskov in the file you modified, there is still a bunch of generics to change (for Scalar, Func, etc). You will need to update them too before we can merge this PR

**Comment by victornoel** [comment]
@andreoss the fact we are going package by package is because in the past we created one todo per package. All in all, I think it's not so bad, at least it makes it easier to review (apparently not enough because it took the two of us to detect flaws in this PR ^^) since we have to check the whole class during review, not only the changes themselves :)

**Comment by victornoel** [comment]
@andreoss the fact we are going package by package is because in the past we created one todo per package. All in all, I think it's not so bad, at least it makes it easier to review (apparently not enough because it took the two of us to detect flaws in this PR ^^) since we have to check the whole class during review, not only the changes themselves :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1608#issuecomment-858763022))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1608](https://github.com/yegor256/cactoos/issues/1608) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `REV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [1mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @dmitrybarskov[/z](https://www.0crat.com/u/dmitrybarskov): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231608%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) resigned from [#1608](https://github.com/yegor256/cactoos/issues/1608), since the job is not in scope anymore

**Pull request merged**
