### PR TITLE
#512 Up to 2018. Happy New Year!

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #512 .

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#513` is now in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Oops! Not enough funds available in the project

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#513` assigned to @allanws  ([profile](http://www.0crat.com/u/allanws})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by allanws** [comment]
@yegor256 , I believe there is nothing else to do on this one. Please, double check and proceed to merge it. 
Thanks.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#513` is now out of scope.

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6615](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @allanws, total is [+30](http://www.0crat.com/u/allanws).

**Pull request merged**
