### PR TITLE
#251: Let's do ReverseIterableTest use JoinedText

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #251 .

### CODE REVIEW

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@fabriciofx looks like Rultor is having problems because of the name of your branch: `#251`. I would recommend to report this bug to rultor repo and rename the branch.

**Comment by fabriciofx** [comment]
@yegor256 Ok.

**Comment by fabriciofx** [comment]
Closed because this PR was renamed to `251` (PR #259).

**Pull request closed without merging**
