### PR TITLE
#352 : Declarative Formatted Text

### PR DESCRIPTION
**Pull request by memoyil**
Declarative Formatted Text

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#402` is in scope.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 2f52b52 2017-08-17T05:56:32
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:yegor256/cactoos#402` is already in scope
	at com.zerocracy.pm.scope.Wbs.add(Wbs.java:79)
	at com.zerocracy.pm.scope.Wbs$add$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.add_job_to_wbs.exec(add_job_to_wbs.groovy:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reactive.brigade.S...
```

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#402` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#402`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#402` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#402`, please stop working.

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#402`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#402` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#402`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#402` assigned to @kkamkou. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#402` assigned to @allanws  ([profile](http://www.0crat.com/u/allanws})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by allanws** [comment]
@yegor256 I am not sure what to do on this one. I opened a ticket about the error described above. Is there anything else to do?

**Comment by allanws** [comment]
@yegor256, just poking you again about my latest comment. Please let me know if you have any question.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT e8fd8525 2018-01-08T11:53:03
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/scope/wbs/remove_job_from_wbs.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/scope/wbs/remove_job_from_wbs.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(Un...
```

Cc @yegor256

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6630](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @allanws, total is [+60](http://www.0crat.com/u/allanws).

**Comment by memoyil** [comment]
@yegor256 Thanks

**Pull request merged**
