### PR TITLE
(#561) override close() method of WriterAsOutputStream

### LINKED ISSUE #561: WriterAsOutputStream does not close the enclosed Writer
`WriterAsOutputStream` does not override `close()`, hence leaving the enclosed writer open. 

Example writing contents to a file and then deleting the file:
```java
        final Path temp = Files.createTempFile("", "");
        new TextOf(
            new TeeInput(
                new ResourceOf("org/cactoos/large-text.txt"),
                new OutputTo(
                    new WriterAsOutputStream(
                        new OutputStreamWriter(
                            new FileOutputStream(temp.toFile()),
                            StandardCharsets.UTF_8
                        ),
                        StandardCharsets.UTF_8,
                        345
                    )
                )
            )
        ).asString();
        Files.delete(temp);    //IOException "the file is being used by another process"
```

### PR DESCRIPTION
**Pull request by rexim**
Close #561

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#603](https://github.com/yegor256/cactoos/issues/603) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#603](https://github.com/yegor256/cactoos/issues/603) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by neonailol** [comment]
@rultor good to merge

**Comment by neonailol** [comment]
@yegor256 please take a look at this

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+450](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#603](https://github.com/yegor256/cactoos/issues/603) is now out of scope

**Pull request merged**
