### PR TITLE
#1416: Migration to Junit 5

### PR DESCRIPTION
**Pull request by andreoss**
Per #1416:

- Migrate simpler tests for Junit 5
- Leave a todo to migrate the rest

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1451](https://github.com/yegor256/cactoos/issues/1451) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/c983bb8e-cc39-4827-8a85-f5de00decb36); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @victornoel[/z](https://www.0crat.com/u/victornoel) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Review by fabriciofx — CHANGES_REQUESTED** [review]
@andreoss Why not migrate everything once time? If all change is something like that (just change the import name and remove public modifier), although it's a huge diff, it's simple and can be easily with `sed` @victornoel WDYT?

**Comment by victornoel** [comment]
@andreoss @fabriciofx I agree, if the change can be done easily in one command, let's just do it. The important thing is that:
- it should be easily reviewable
- it should pass the CI of course

If it is not easily reviewable, then let's do it in multiple times, both junit 5 and 4 can live together I believe.

**Comment by fabriciofx** [comment]
@victornoel I agree with all requeriments. @andreoss please, can you check if all the changes is easily as said? if yes, can you do it once time?

**Comment by andreoss** [comment]
@fabriciofx I made this changes with this command https://gist.github.com/andreoss/07a248a0b6fb0d1b44647c02a9391969. 
The more complex cases (such as Rules, and exceptions) are left as a todo. 
I believe that you can skim though this diff within 15 minutes, but you can also just review the script which made these changes.

**Comment by fabriciofx** [comment]
@andreoss right. As the change isn't trivial (by a just one command) I'll accept this PR and the puzzle left will guide us to continue the refactoring. Thanks and congratulations for this job! :)

**Review by fabriciofx — APPROVED** [review]
@victornoel it seems fine. Can you merge it, please?

**Comment by victornoel** [comment]
@andreoss @fabriciofx thank you

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
