### PR TITLE
Added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by g4s8**
See [contributing guidelines](https://github.com/blog/1184-contributing-guidelines) from Github.

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#433` is in scope.

**Comment by filfreire** [comment]
@g4s8 we could also mention some kind of rule for commit messages. Specially the ones related to a certain github issue. What do you think?

@yegor256 FYI

**Comment by g4s8** [comment]
@filfreire sure, lets declare a template for commit message. I think it can be:
```
#<issue-number> - <short description>
```

@filfreire @yegor256 what do you think?

**Comment by filfreire** [comment]
@g4s8 it should have a space before the `#` character, so that it's not picked up as a comment in VIM or other text editors.
``` #<issue-number> - <short description>```

**Comment by yegor256** [comment]
@g4s8 yes, I like the template.

**Comment by yegor256** [comment]
@g4s8 @filfreire I'm using just `#123 hello world`, without the dash

**Comment by yegor256** [comment]
@g4s8 @filfreire maybe we need these guys: https://gitcop.com/ :)

**Comment by filfreire** [comment]
@g4s8 @yegor256 it's supposedly free for OS. Why not?
We could create issues in Tacit, Cactoos and Rultor to link to Gitcop. @yegor256 can you follow-up afterwards?

**Comment by filfreire** [comment]
@g4s8 created issue to account for this work
https://github.com/yegor256/cactoos/issues/435

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#433` assigned to @fabriciofx, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@fabriciofx resigned from `gh:yegor256/cactoos#433`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#433` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#433` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6035](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1260](http://www.0crat.com/u/kkamkou).

**Pull request merged**
