### PR TITLE
(#901) ListIterator null-free class implementation

### PR DESCRIPTION
**Pull request by tomascury**
#901
All done

1. 'org.cactoos.list.NoNulls' returns a null-free `ListIterator'.
2. Iterators returned by 'org.cactoos.list.NoNulls' are Immutable

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1072](https://github.com/yegor256/cactoos/issues/1072) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1072](https://github.com/yegor256/cactoos/issues/1072) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/2c627c52-21e7-49b3-9553-39d8e1854f80); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by tomascury** [comment]
@llorllale  I'm trying to create the pull request, but I must be missing something because it always fails on code check.
I was trying hard to improve the test unit coverage, but it's not working. What am I doing wrong?
Thanks!

**Comment by llorllale** [comment]
@tomascury look at the coverage [here](https://codecov.io/gh/yegor256/cactoos/pull/1072/changes)

**Comment by llorllale** [comment]
@tomascury ping

**Comment by llorllale** [comment]
@tomascury closed due to inactivity

**Comment by 0crat** [comment]
Job [#1072](https://github.com/yegor256/cactoos/issues/1072) is not in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), can't retrieve data and time of add

**Comment by 0crat** [comment]
Code review was too long (33 days), architects (@llorllale) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Job [#1072](https://github.com/yegor256/cactoos/issues/1072) is not in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1072](https://github.com/yegor256/cactoos/issues/1072) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by sereshqua** [comment]
quality bad

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request closed without merging**
