### PR TITLE
(#1144) Replace the TeeInputHasResult with the InputHasContent and de…

### LINKED ISSUE #1144: TeeInputHasResult.java:42-44: Replace the usage of the...
The puzzle `1086-77b05812` from #1086 has to be resolved: 

https://github.com/yegor256/cactoos/blob/fe264a47b70d371efe89f40708735e852acded0b/src/test/java/org/cactoos/io/TeeInputHasResult.java#L42-L44

The puzzle was created by Victor Noël on 08-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by aivinog1**
This is a fix to #1144.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1157](https://github.com/yegor256/cactoos/issues/1157) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1157](https://github.com/yegor256/cactoos/issues/1157) is assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/71a78ff5-ab53-4328-b67e-ca62e0303b0f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@rultor merge

**Comment by vzurauskas** [comment]
@aivinog1 Build failed for some reason.

**Comment by aivinog1** [comment]
@vzurauskas I've tried to fix it, but the build in the Travis did not work: https://github.com/yegor256/cactoos/issues/1172.

**Comment by 0crat** [comment]
This pull request [#1157](https://github.com/yegor256/cactoos/issues/1157) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/2a258962-9c12-4fad-9a05-3cefcf96d12d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@paulodamaso please, check it out why travis fail. I cant' approve a PR that fails build.

**Comment by aivinog1** [comment]
@fabriciofx I have to write an additional test because of coverage became less than it was for no reason.

**Comment by aivinog1** [comment]
@fabriciofx can you review this, please?

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) all `QA`s are on vacation. Please handle that.

**Comment by 0crat** [comment]
The job [#1157](https://github.com/yegor256/cactoos/issues/1157) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
