### PR TITLE
#1235 - Added more Assertions to tests.

### PR DESCRIPTION
**Pull request by vzurauskas**
PR for #1235 

Replaced some `assertThat` method usages with `Assertion` in `io` package. Updated `todo`.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1323](https://github.com/yegor256/cactoos/issues/1323) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/aca221a6-2e16-4018-8ca0-e12869010f7b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@vzurauskas Thank you

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
