### PR TITLE
added maintenance stats badges

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#678](https://github.com/yegor256/cactoos/issues/678) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#678](https://github.com/yegor256/cactoos/issues/678) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/491957125). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by neonailol** [comment]
@rultor merge

**Comment by ashtonhogan** [comment]
@yegor256 These show average time to resolve issue and percentage of issues still open

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@ashtonhogan According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please provide description of what was done with link to original issue.

**Comment by ypshenychka** [comment]
@neonailol According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code. Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by neonailol** [comment]
@yegor256 all good, this can be merged

**Comment by yegor256** [comment]
@neonailol there is nothing to merge here anymore, the PR is closed

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ypshenychka** [comment]
@yegor256 As far as I understand no more work will be done in scope of this PR, right?

**Comment by yegor256** [comment]
@ypshenychka correct, the quality is bad here

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/678#issuecomment-368813368))

@yegor256 The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#678](https://github.com/yegor256/cactoos/issues/678), please stop working. Reason for job resignation: Order was cancelled

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/678#issuecomment-368815738))

@yegor256 The job [#678](https://github.com/yegor256/cactoos/issues/678) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/cactoos/issues/678#issuecomment-368822329))

@ypshenychka Job `gh:yegor256/cactoos#678` is not assigned, can't get start time

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+853](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
