### PR TITLE
#985 Because dates already been updated found out that dates verifica…

### PR DESCRIPTION
**Pull request by aivinog1**
This fix for #985. Found out that dates already changed and add new todo to fix a dates verification.

### CODE REVIEW

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @llorllale[/z](https://www.0crat.com/u/llorllale) please review this and merge or reject

**Comment by llorllale** [comment]
@aivinog1 I'm gonna need something more substantive than this. Did you attempt to fix the problem?

**Comment by aivinog1** [comment]
@llorllale Okay, I'll try to fix this.

**Comment by aivinog1** [comment]
@llorllale I found a reason why plugin not works. It's simple absent in the `build/plugins` section, it was only in `build/pluginManagement` section

**Comment by aivinog1** [comment]
@0crat wait  #1148

**Comment by 0crat** [comment]
> @0crat wait #1148  ([here](https://github.com/yegor256/cactoos/issues/1146#issuecomment-505366221))

@aivinog1 Job `gh:yegor256/cactoos#1146` is not assigned, can't get performer

**Comment by llorllale** [comment]
@aivinog1 awesome!

Please rebase on `master` and let's wait for confirmation from the travis and appveyor builds

**Comment by aivinog1** [comment]
@llorllale done.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1146` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
