### PR TITLE
Readme: added questions

### PR DESCRIPTION
**Pull request by g4s8**

### CODE REVIEW

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#431` is already in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#431` assigned to @fabriciofx, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
@fabriciofx resigned from `gh:yegor256/cactoos#431`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#431` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#431` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @yegor256, total is [+6035](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+1260](http://www.0crat.com/u/kkamkou).

**Pull request merged**
