### PR TITLE
Resource input

### PR DESCRIPTION
**Pull request by g4s8**
Resource input that can read class resources
Part of #13

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8 I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@g4s8 first, let's name it `ResourceAsInput` to be consistent. Second, let's get rid of that test file and use something else, already available in `target/test-classes` or `target/classes`.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor try to merge

**Pull request merged**
