### PR TITLE
#1415: Run tests on Java 11

### PR DESCRIPTION
**Pull request by andreoss**
Per #1415
- Fix complilation on 11 ~~& 14~~
- Add 11 ~~& 14~~ to Github actions

### CODE REVIEW

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @victornoel[/z](https://www.0crat.com/u/victornoel) please review this and merge or reject

**Comment by victornoel** [comment]
@andreoss thx, but why support Java 14? it's not LTS I believe?

**Comment by andreoss** [comment]
@victornoel Indeed, there's no need for 14 as it's already reached End of Availability [1]. If we want to test on the latest java release, it should be 15.


1: https://adoptopenjdk.net/support.html#roadmap

**Comment by victornoel** [comment]
@andreoss ok, let's do LTSs + latest :) thx

**Comment by victornoel** [comment]
@andreoss ok, let's do LTSs + latest :) thx

**Comment by andreoss** [comment]
@victornoel Replaced 14 with 15

**Comment by victornoel** [comment]
@andreoss thx, surprinsingly, there is a test failing on windows, but I think it's because the test is flaky, I've re-run the CI, if it passes we will merge and I will create a ticket to fix the test

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1491` is not assigned, can't get performer

**Pull request merged**
