### PR TITLE
replaced all Arrays.asList with new ListOf<>()

### PR DESCRIPTION
**Pull request by ashtonhogan**
This is for this [issue](https://github.com/yegor256/cactoos/issues/769). There is still [one more](https://github.com/yegor256/cactoos/blob/b4223ce3e096424397e33058568b587844d93b24/src/main/java/org/cactoos/iterable/IterableOf.java#L50) left. I've created a [new issue](https://github.com/yegor256/cactoos/issues/773) for this one because it has a deeper problem that needs to be solved.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#772](https://github.com/yegor256/cactoos/issues/772) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#772](https://github.com/yegor256/cactoos/issues/772) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/1061951357); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by ashtonhogan** [comment]
@neonailol Do you know how this checkstyle error can be fixed?

```
org\cactoos\collection\MappedTest.java[48]: Class Data Abstraction Coupling is 8 (max allowed is 7) classes [AbstractCollection, BehavesAsCollection, Endless, IterableOf, ListOf, Mapped, TextOf, UpperText]. (ClassDataAbstractionCouplingCheck)
```

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#772](https://github.com/yegor256/cactoos/issues/772), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
This pull request [#772](https://github.com/yegor256/cactoos/issues/772) is assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/1161976598); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by SharplEr** [comment]
@llorllale good to merge.
@ashtonhogan It's better to use `pdd` than create a separate issue in such case.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#772](https://github.com/yegor256/cactoos/issues/772) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by SharplEr** [comment]
@elenavolokhova confirm

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
