### PR TITLE
#1500: Remove duplicated code from `MaxOf` & `MinOf`

### PR DESCRIPTION
**Pull request by andreoss**
Per #1500 
- Delegate to primary constructor for Number

### CODE REVIEW

**Review by fabriciofx — APPROVED** [review]
@andreoss Congratulations for this excellent code! Awesome! @victornoel It seems good to merge. WDYT?

**Comment by victornoel** [comment]
@andreoss very nice

@fabriciofx thx

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1501](https://github.com/yegor256/cactoos/issues/1501), since the job is not in scope anymore

**Pull request merged**
