### PR TITLE
#799 removed puzzle

### PR DESCRIPTION
**Pull request by Vatavuk**
Removed puzzle for issue #799

### CODE REVIEW

**Comment by 0crat** [comment]
@Vatavuk this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @llorllale[/z](https://www.0crat.com/u/llorllale) please review this and merge or reject

**Comment by Vatavuk** [comment]
@llorllale I forgot to remove puzzle for #799 in merged PR #842.  Could you please merge this.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/858#issuecomment-388577256))

@llorllale There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25988aaf-ee2f-4146-a0f5-fd10756db4a7, thread: AsyncFlush-2
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/vatavuk.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1321952601, Type: 'Close job', Author: llorllale

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/858#issuecomment-388577407))

@llorllale There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25988aaf-ee2f-4146-a0f5-fd10756db4a7, thread: AsyncFlush-7
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/vatavuk.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1321955687, Type: 'Close job', Author: llorllale

**Comment by llorllale** [comment]
@Vatavuk do you mind waiting a little longer to see if this error with 0crat is resolved? I really don't want payments to be handed out after merging this one

**Comment by Vatavuk** [comment]
@llorllale np

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/858#issuecomment-388824303))

@llorllale The job is not in WBS, won't close the order

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/858#issuecomment-388825460))

@llorllale There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f819ff16-dfc6-408f-9a1e-cbbc153fc2a3, thread: AsyncFlush-6
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/cactoos#858] declared for identity constraint of element "blanks".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1341357486, Type: 'Close job', Author: llorllale

**Comment by llorllale** [comment]
@0crat refuse

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8e1fc06d-5a42-48df-abcc-d91068234970, thread: BkParallel-7
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 3 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1341359002">
   <created>2018-05-14T13:59:01.296Z</created>
   <type>Cancel order</type>
   <token>github;yegor256/cactoos;858;388826320</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/cactoos#858</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">858</param>
      <param name="comment">388826320</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#858, Comment: 388826320

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8e1fc06d-5a42-48df-abcc-d91068234970, thread: BkParallel-7
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 3 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1341359002">
   <created>2018-05-14T13:59:01.296Z</created>
   <type>Cancel order</type>
   <token>github;yegor256/cactoos;858;388826320</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/cactoos#858</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">858</param>
      <param name="comment">388826320</param>
   </params>
</claim>

com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 3 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1341359002">
   <created>2018-05-14T13:59:01.296Z</created>
   <type>Cancel order</type>
   <token>github;yegor256/cactoos;858;388826320</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/cactoos#858</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">858</param>
      <param name="comment">388826320</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#858, Action: `created`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8e1fc06d-5a42-48df-abcc-d91068234970, thread: BkParallel-5
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 4 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1341359005">
   <created>2018-05-14T13:59:31.271Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;858;388826367</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/cactoos#858</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">858</param>
      <param name="comment">388826367</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#858, Comment: 388826367

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8e1fc06d-5a42-48df-abcc-d91068234970, thread: BkParallel-5
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 4 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1341359005">
   <created>2018-05-14T13:59:31.271Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;858;388826367</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/cactoos#858</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">858</param>
      <param name="comment">388826367</param>
   </params>
</claim>

com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 4 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1341359005">
   <created>2018-05-14T13:59:31.271Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;858;388826367</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/cactoos#858</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">858</param>
      <param name="comment">388826367</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#858, Action: `created`

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/858#issuecomment-388826320))

@llorllale Job `gh:yegor256/cactoos#858` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/858#issuecomment-388826320))

@llorllale Job `gh:yegor256/cactoos#858` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/858#issuecomment-388826367))

@llorllale There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8e1fc06d-5a42-48df-abcc-d91068234970, thread: AsyncFlush-7
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/cactoos#858] declared for identity constraint of element "blanks".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1341359005, Type: 'Close job', Author: llorllale

**Pull request merged**
