### PR TITLE
(#958) Don't use compound names for decorators

### PR DESCRIPTION
**Pull request by llorllale**
For #958:
* Fixed class naming on io and iterable packages as per https://github.com/yegor256/cactoos/issues/913#issuecomment-402332247

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#963](https://github.com/yegor256/cactoos/issues/963) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#963` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#963](https://github.com/yegor256/cactoos/issues/963) is now out of scope

**Pull request merged**
