### PR TITLE
#622 Fix javadoc for all Sync... classes

### PR DESCRIPTION
**Pull request by Maratori**
This is fix of wrong javadocs in Sync... classes (see Issue #622).

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#623](https://github.com/yegor256/cactoos/issues/623) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#623` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#623](https://github.com/yegor256/cactoos/issues/623) is now out of scope

**Pull request merged**
