### PR TITLE
(#1502) Added @FunctionalInterface to all the cactoos functional interfaces

### PR DESCRIPTION
**Pull request by dearrudam**
#1502
- Added the @FunctionalInterface annotation into all the cactoos interfaces that could be considered a functional interface.

### CODE REVIEW

**Comment by 0crat** [comment]
@dearrudam[/z](https://www.0crat.com/u/dearrudam) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @victornoel[/z](https://www.0crat.com/u/victornoel) please review this and merge or reject

**Comment by victornoel** [comment]
@dearrudam thank you and welcome to cactoos :)

**Comment by victornoel** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1552` is not assigned, can't get performer

**Pull request merged**
