### PR TITLE
1362 Work on replacing MatcherAssert to Assertion

### PR DESCRIPTION
**Pull request by a-korzhov**
#1362 
 - Replaced MatcherAssert.assertThat functions to Assertion objects

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1364](https://github.com/yegor256/cactoos/issues/1364) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/29661c86-dcff-42a5-bac9-2e4fb351df4a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by a-korzhov** [comment]
> @a-korzhov that seems good, two comments:
> 
> * remove the existing todo that you are solving and add a new one if there is more work to be done: you can just change the existing one by replacing the id of the ticket at the beginning of the todo with the one you are  now solving
> * can you also edit the description of this PR to have a link to the ticket you are currently solving?

Edited description and add new ticket

**Comment by victornoel** [comment]
@a-korzhov perfect, thx

@paulodamaso looks good to me

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 16 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@victornoel please make sure you will find at least 3 issues during next CR, thanks!

**Comment by victornoel** [comment]
@sereshqua I will

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
