### PR TITLE
Add `equals`, `hashCode` and `toString` to `Constant`

### PR DESCRIPTION
**Pull request by andreoss**
- Add `toString`
- Add `equals` and `hashCode`

### CODE REVIEW

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1616#issuecomment-860062924))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1616](https://github.com/yegor256/cactoos/issues/1616) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231616%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by victornoel** [comment]
@andreoss I'm not exactly sure what would justify having Scalar objects implement those methods... I know that `Text` has such methods implemented and even there I'm not sure it's relevant.

The only places where they make sense to me is for classes used to purely store data, such as collections.

Did you have a particular need in mind for this PR?

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by andreoss** [comment]
@victornoel `Constant` (as many `Scalar` implementations) is troublesome to use without calling `value()`. 
I expect that two identical constants should be equal at least. `toString` simplifies logging, as I primarily use `Constant` as configuration defaults.

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) everybody who has role `REV` is banned at [#1616](https://github.com/yegor256/cactoos/issues/1616); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Pull request closed without merging**
