### PR TITLE
#201: NormalizedText

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #201 :

`NormalizedText` introduced.

### CODE REVIEW

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@fabriciofx where did you get that? In Apache Commons?

**Comment by fabriciofx** [comment]
@yegor256 Yeah, in the method `StringUtils.normalizeSpace()` as you can read [here](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#normalizeSpace-java.lang.String-).

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
