### PR TITLE
#358 : Right and Left Trim Implementation

### PR DESCRIPTION
**Pull request by memoyil**
Implementing right and left trim

### CODE REVIEW

**Comment by yegor256** [comment]
@memoyil please update README also

**Comment by memoyil** [comment]
@yegor256 Done.

**Comment by yegor256** [comment]
@memoyil see https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#stripStart-java.lang.String-java.lang.String-

**Comment by memoyil** [comment]
@yegor256 Updated

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
