### PR TITLE
IterableOf, MapEntry and MapEnvelope started using HashCode instead o…

### PR DESCRIPTION
**Pull request by catdog905**
…f thir own hashing

#1440

### CODE REVIEW

**Comment by catdog905** [comment]
@yegor256 Hello! Could you check this PR that may close #1440 issue?

**Comment by yegor256** [comment]
@catdog905 many thanks for your contribution! Please, run `mvn clean install -Pqulice` and then fix the code formatting issues

**Comment by catdog905** [comment]
@yegor256 Hello! I've pulled master and seems all checks have passed. Is there anything left to do before merging?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@catdog905 thanks!

**Pull request merged**
