### PR TITLE
(#1033) Replace use of MatcherAssert.assertThat with Assertion from cactoos-matchers

### PR DESCRIPTION
**Pull request by vzurauskas**
This is for #1033.

I replaced some of the `MatcherAssert#assertThat` usages with `Assertion` from cactoos-matchers. There is still a lot code to replace - I added a `@todo` for that.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1111](https://github.com/yegor256/cactoos/issues/1111) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1111](https://github.com/yegor256/cactoos/issues/1111) is assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C63314D6Z/46b52fd5-68ea-4509-b4ab-5dd3da6b8526); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1111` already assigned to @ilyakharlamov, can't assign to @ilyakharlamov

**Comment by ilyakharlamov** [comment]
checked, it's a syntax change, not a single line of logic is affected
@llorllale it's good to merge

**Comment by vzurauskas** [comment]
@llorllale ping

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1111](https://github.com/yegor256/cactoos/issues/1111) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by sereshqua** [comment]
@ilyakharlamov you haven't found any issues during a code review; can you please make sure that next time you will try to find at least 3 issues as written in [policy](http://www.zerocracy.com/policy.html#30)?

**Comment by ilyakharlamov** [comment]
@sereshqua sure I will

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
