### PR TITLE
#500 Eclipse cannot infer type arguments in FilteredTest

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #500.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#501` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#501`.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#501` is now out of scope.

**Pull request merged**
