### PR TITLE
#648 added equals, hashCode and toString methods to ListEnvelope

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Fixing #648

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#663](https://github.com/yegor256/cactoos/issues/663) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#663](https://github.com/yegor256/cactoos/issues/663) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C63314D6Z/471703101). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by svendiedrichsen** [comment]
We should rather stick with the List equals/hashcode Javadoc. https://docs.oracle.com/javase/8/docs/api/java/util/List.html#equals-java.lang.Object- as stated in the issue.

**Comment by amihaiemil** [comment]
@svendiedrichsen I see, ok

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@svendiedrichsen According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please edit the description to be more informative.

**Comment by ypshenychka** [comment]
@svendiedrichsen According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your [message](https://github.com/yegor256/cactoos/pull/663#issuecomment-366301293) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka I confirm I'll try to find more issues in future PRs (although we should be a bit flexible with that rule, these PRs were rather small and a few of them were even cosmetic changes)

**Comment by amihaiemil** [comment]
@ypshenychka verdict here? :D

**Comment by ypshenychka** [comment]
@amihaiemil Waiting on @svendiedrichsen to make changes according to my remarks.

**Comment by amihaiemil** [comment]
@svendiedrichsen Can you pls make the correction?

**Comment by ypshenychka** [comment]
@svendiedrichsen Thank you for making corrections. In future please ping me whne you make changes, so I could proceed with QA review.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+375](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+820](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10364](https://www.0crat.com/u/yegor256)

**Pull request merged**
