### PR TITLE
#563 ReaderAsBytes not closing the enclosed Reader

### PR DESCRIPTION
**Pull request by alex-semenyuk**

### CODE REVIEW

**Comment by alex-semenyuk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/569#issuecomment-362799516))

@alex-semenyuk This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#569](https://github.com/yegor256/cactoos/issues/569) is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#569` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#569](https://github.com/yegor256/cactoos/issues/569) was not in scope

**Pull request closed without merging**
