### PR TITLE
(#1015) Move more NoNulls to their own file

### PR DESCRIPTION
**Pull request by victornoel**
This is for #1015. Nothing special except there was no test for `BiProcNoNulls` and I didn't add them since `BiProc` going to be removed (see https://github.com/yegor256/cactoos/issues/1015#issuecomment-478182654).

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1090](https://github.com/yegor256/cactoos/issues/1090) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@victornoel 

> no test for BiProcNoNulls and I didn't add them since BiProc going to be removed

Let's not assume `Proc` and `BiProc` will *definitely* be removed because #915 will require input from the community (whoever answers the call).

So either add quick tests or leave a puzzle, up to you.

**Comment by victornoel** [comment]
@llorllale I've added some tests

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1090` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1090](https://github.com/yegor256/cactoos/issues/1090) is now out of scope

**Pull request merged**
