### PR TITLE
#573 improvement IsBlank

### PR DESCRIPTION
**Pull request by VsSekorin**
As per #573

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#574](https://github.com/yegor256/cactoos/issues/574) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#574](https://github.com/yegor256/cactoos/issues/574) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by fabriciofx** [comment]
@yegor256 This PR seems fine to me. I accept it.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), total is [+375](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8375](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
This pull request [#574](https://github.com/yegor256/cactoos/issues/574) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#574](https://github.com/yegor256/cactoos/issues/574), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#574](https://github.com/yegor256/cactoos/issues/574) is now out of scope

**Comment by 0crat** [comment]
Job [#574](https://github.com/yegor256/cactoos/issues/574) was not in scope

**Pull request merged**
