### PR TITLE
Ascii text#235

### PR DESCRIPTION
**Pull request by ixmanuel**
See #235 

```java
String ascii = new AsciiText("Ç©mm©ñ").asString(); // Common
```

It is a requirement for SluggedText.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@ixmanuel this looks like something crazy to me :) Who else is doing this? Guava? Apache?

**Comment by ixmanuel** [comment]
Yes, maybe you're right. I wanted to contribute with SluggedUrl and thus, it was a requirement for managing unicodes. Then, I made a research and I found a practical and mature library: [junidecode](https://github.com/gcardone/junidecode) but, Cactoos has no dependencies. Then, I searched for something more simple: [Stringy](https://github.com/danielstjules/Stringy/tree/2.3.1) and I only imported its mapping table and I made a reference to its [license](https://github.com/danielstjules/Stringy/blob/2.3.1/LICENSE.txt).

But yes, it might be for a library based on Cactoos because this implementation doesn't support Chinese but it tries to make the transliteration as best as it can but not correctly for some languages.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-04T07:36:32
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:197)
	at com.zerocracy.farm.reactive.RunnableWithTrigger.run(RunnableWithTrigger.java:52)
	at java....
```

**Pull request closed without merging**
