### PR TITLE
Fat PR

### PR DESCRIPTION
**Pull request by g4s8**
Use encoding for text to bytes conversion and vice verse.
Class resource input.
First element scalar.
Fixed set.

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8 I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@g4s8 this definitely is a fat PR. It has so many features and most of them are great. Can you please break it to smaller PRs? Otherwise, I will just annoy you with my comments. I have many of them :)

**Comment by yegor256** [comment]
@g4s8 I actually started to create that `ResourceAsInput` today :) So, if you hurry up, I will merge your branch and won't create mine. I need that class in one of my projects.

**Comment by g4s8** [comment]
@yegor256 ok, I'll submit them soon

**Pull request closed without merging**
