### PR TITLE
#737 added more ctors to Or

### PR DESCRIPTION
**Pull request by Vatavuk**
Added more ctors to `Or` for issue #737

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#752](https://github.com/yegor256/cactoos/issues/752) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#752](https://github.com/yegor256/cactoos/issues/752) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/901666420); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by Vatavuk** [comment]
@yegor256 Can you assign someone else to review this PR? @fabriciofx Is not responding to any PRs almost a month.

**Comment by memoyil** [comment]
@Vatavuk https://github.com/yegor256/cactoos/pull/742 I opened same pr about 15 days ago. You can close this one.

**Comment by yegor256** [comment]
@Vatavuk seems to be a duplicate?

**Comment by Vatavuk** [comment]
@yegor256 I will close this one. Please reassign issue #737 to @memoyil

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#752](https://github.com/yegor256/cactoos/issues/752) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request closed without merging**
