### PR TITLE
(#1141) Reducing a number of an iteration in tests.

### LINKED ISSUE #1141: SyncedTest.java:41-48: Continue speeding up the `mvn...
The puzzle `1115-b0c94327` from #1115 has to be resolved: 

https://github.com/yegor256/cactoos/blob/78d0e803f7c61f59b7c14a2ca502ba32eade8456/src/test/java/org/cactoos/iterator/SyncedTest.java#L41-L48

The puzzle was created by Victor Noël on 30-May-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by aivinog1**
This PR fixes #1141. If I understand issue correctly we need just reduce a number of iterations.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1150](https://github.com/yegor256/cactoos/issues/1150) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1150](https://github.com/yegor256/cactoos/issues/1150) is assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/a5eef6bd-8d10-4158-bb99-7bde89d09955); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by aivinog1** [comment]
@0crat wait for `REV`

**Comment by 0crat** [comment]
> @0crat wait for `REV` ([here](https://github.com/yegor256/cactoos/issues/1150#issuecomment-507580466))

@aivinog1 @aivinog1[/z](https://www.0crat.com/u/aivinog1) you can't register impediment for this job

**Comment by llorllale** [comment]
@aivinog1 as per @victornoel 

> it seems most of the tries results in 0 overlapping thread. This is why so much tries are needed in the for loop for the tests to be sound.

So I would expect other changes to ensure that "overlapping" does in fact actually occur even if we reduce the loop count

**Comment by victornoel** [comment]
@aivinog1 I concur with @llorllale : the whole point of this ticket is to be confident in the test while doing less loops. By only reducing the loops, it's making the test useless. The todo in the issue is quite clear on how to "verify" that there are overlaps.

**Comment by aivinog1** [comment]
@llorllale and @victornoel Thanks. I'll reread this todo again.

**Comment by aivinog1** [comment]
@victornoel This issue is still not clear for me. I'll refuse the task.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#1150](https://github.com/yegor256/cactoos/issues/1150) is not in the agenda of @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), can't inspect

**Comment by 0crat** [comment]
Code review was too long (9 days), architects (@llorllale) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#1150](https://github.com/yegor256/cactoos/issues/1150) is now out of scope

**Comment by 0crat** [comment]
Pull request [#1150](https://github.com/yegor256/cactoos/issues/1150) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request closed without merging**
