### PR TITLE
#370: endless Joined

### PR DESCRIPTION
**Pull request by Zefick**
My alternative fix for #370.

I discovered that the code of Joined iterators have a premature pessimization in both next() and hasNest() methods. It iterates items from the start to a first non-empty iterator every time and thus it doesn't hava each own state but abuses the states of items instead. I believe it's wrong. Iterator has a state by definition and there is no reasons to hide the state in such unobvoius manner to make code looks "immutable".

Performance is not the main goal of the fix despite it increased a lot. Mainly  it makes the code less coupled and fixed the bugs such #370 in advance.

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` is in scope.

**Comment by memoyil** [comment]
@Zefick You should run on your environment first (mvn clean install -Pqulice) before making a pull request to avoid this errors.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#405`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#405`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#405`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#405`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` assigned to @kkamkou. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` assigned to @kkamkou  ([profile](http://www.0crat.com/u/kkamkou})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` assigned to @neonailol  ([profile](http://www.0crat.com/u/neonailol})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment]
@yegor256 will you accept this code?

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#405` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @neonailol, total is [+30](http://www.0crat.com/u/neonailol).

**Comment by 0crat** [comment]
Payment to ARC for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256, total is [+6710](http://www.0crat.com/u/yegor256).

**Pull request merged**
