### PR TITLE
(#1502) Fixed the author's email 

### PR DESCRIPTION
**Pull request by dearrudam**
#1502

- Sorry, everyone! I must thank @andreoss for letting me know that the commits that I performed are pointing to another email address. That's the reason why I'm performing this PR again.

### CODE REVIEW

**Comment by andreoss** [comment]
@dearrudam I don't think it necessary. Your commits are already in `master` and the only way to amend them now is to history-rewrite by rebasing.

**Comment by dearrudam** [comment]
@victornoel this PR is related to PR #1552 that you've approved.

**Comment by dearrudam** [comment]
@andreoss Could it bring problems to the ZC platform?

**Comment by dearrudam** [comment]
I mean, regarding the reputation for me?

**Comment by 0crat** [comment]
@dearrudam[/z](https://www.0crat.com/u/dearrudam) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @victornoel[/z](https://www.0crat.com/u/victornoel) please review this and merge or reject

**Comment by victornoel** [comment]
@dearrudam don't worry, it's not important, things like that happen. As @andreoss said, it's already on master, so it can't be changed.

But it's ok, it has no impact on zerocracy or whatever, this is how it works: when you get a ticket assigned, only when the ticket is closed, you get the reputation, money, etc

So for example for the PR we already merged #1552, the corresponding ticket assigned #1502 has to be closed now. Usually, you have to ask, in the ticket, reporter to close it. Until then you won't get any reputation.

So I will close this PR for now as it is not needed :)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1553` is not assigned, can't get performer

**Pull request closed without merging**
