### PR TITLE
#368: ready to release

### PR DESCRIPTION
**Pull request by yegor256**
see #386: I polished the code, deleted `CharactersOf` and made some minor changes.

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#369` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+915](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#369` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#369`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#369` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @kkamkou, total is [+930](http://www.0crat.com/u/kkamkou).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#369` is not in scope

**Pull request merged**
