### PR TITLE
#537 Refactored InputWithFallbackTest to always fallback to the specified fallback Input

### PR DESCRIPTION
**Pull request by driver733**
As per #537

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#583](https://github.com/yegor256/cactoos/issues/583) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#583](https://github.com/yegor256/cactoos/issues/583) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by neonailol** [comment]
@yegor256 good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+195](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8770](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#583](https://github.com/yegor256/cactoos/issues/583) is now out of scope

**Pull request merged**
