### PR TITLE
#1235 MatcherAssert.assertThat with Assertion from cactoos-matchers

### PR DESCRIPTION
**Pull request by dgarus**
[#1235 ](https://github.com/yegor256/cactoos/issues/1235)

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1322](https://github.com/yegor256/cactoos/issues/1322) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/7a872f93-8bfc-4129-b14d-24ed1af99a9a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso please refuse that PR since @dgarus is not assigned to this issue anymore and a more complete PR was made with #1323

**Comment by paulodamaso** [comment]
@victornoel Thanks

**Comment by 0crat** [comment]
Pull request [#1322](https://github.com/yegor256/cactoos/issues/1322) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
