### PR TITLE
Replace IOException with Exception

### PR DESCRIPTION
**Pull request by pistriak**
Replaced IOException with Exception

### CODE REVIEW

**Comment by 0crat** [comment]
@pistriak I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor try to merge again

**Pull request closed without merging**
