### PR TITLE
(#1205) Fixing PMD, Checkstyle, Findbugs issues

### PR DESCRIPTION
**Pull request by fanifieiev**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed
  - Title begins with the issue's number, then a short title
  - Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
  - Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).
  - You ran the build locally and it passed (see .travis.yml for all checks performed on PRs)
  - Your commit messages comply with our rules (see .gitlint)

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1207](https://github.com/yegor256/cactoos/issues/1207) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1207](https://github.com/yegor256/cactoos/issues/1207) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/c950cde4-fc65-49ff-a082-ec44a5b1df14); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
Closing this pull request

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1207](https://github.com/yegor256/cactoos/issues/1207) is now out of scope

**Comment by 0crat** [comment]
Pull request [#1207](https://github.com/yegor256/cactoos/issues/1207) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by fanifieiev** [comment]
This pull request was removed by me, as there were some issues, so I created a new one.

**Pull request closed without merging**
