### PR TITLE
#1017 Making NoNulls API consistent

### PR DESCRIPTION
**Pull request by Iprogrammerr**
As described in #1017.

- CollectionNoNulls is now NoNulls, the same holds true for test
- IteratorNoNulls is now NoNulls, the same holds true for test

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1018](https://github.com/yegor256/cactoos/issues/1018) is now in scope, role is `REV`

**Comment by fabriciofx** [comment]
@llorllale I finished review. It's a very simple change, nothing to comment. Can you merge it?

**Comment by llorllale** [comment]
@Iprogrammerr can you increase coverage by that 0.01% we're missing here?

**Comment by Iprogrammerr** [comment]
@llorllale Done.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 28 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1018](https://github.com/yegor256/cactoos/issues/1018) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Pull request merged**
