### PR TITLE
#861 Remove FuncOf.ctr(Proc<X>)

### PR DESCRIPTION
**Pull request by Isammoc**
Pull request for #861 

Remove bad constructor and create puzzles where the solution is not straightforward.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#876](https://github.com/yegor256/cactoos/issues/876) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#876](https://github.com/yegor256/cactoos/issues/876) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361462098); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by Isammoc** [comment]
@paulodamaso Indeed, there are more `null`s than before but with a puzzle specific for each occurence. Each call of the original ctor has to be solved separately and even a day is not enough to solve correctly all the occurences.

**Comment by paulodamaso** [comment]
@Isammoc Tha'ts right, so just fix these coverage problems ad we're good to go.

**Comment by Isammoc** [comment]
@paulodamaso Coverage problems fixed

**Comment by paulodamaso** [comment]
@rultor merge please

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#876](https://github.com/yegor256/cactoos/issues/876) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@Isammoc According to our [Policy](http://www.zerocracy.com/policy.html#42)
> All commit messages have links to issues

Please, confirm that you'll include such links to all commits in future.

**Comment by elenavolokhova** [comment]
@paulodamaso According to our [Policy](http://www.zerocracy.com/policy.html#42)
> The code reviewer found at least three problems in the code
Only two issues were found during review.

Please, confirm that you'll try to follow this rule in future.

**Comment by Isammoc** [comment]
@elenavolokhova Didn't see this requierement, I will do it for next PRs. Thanks

**Comment by paulodamaso** [comment]
@elenavolokhova confirmed, thanks

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
